# Generated by Django 5.0.14 on 2026-08-12 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnquiryStageChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_stage", models.CharField(blank=True, max_length=16)),
                ("to_stage", models.CharField(max_length=16)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("mobile", models.CharField(db_index=True, max_length=20)),
                ("alternate_mobile", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ivr", "IVR / call"),
                            ("whatsapp", "WhatsApp"),
                            ("website", "Website form"),
                            ("walk_in", "Walk-in"),
                            ("referral", "Referral"),
                            ("google", "Google"),
                            ("meta", "Meta"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("campaign", models.CharField(blank=True, max_length=150)),
                ("service_requested", models.CharField(blank=True, max_length=255)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("visited", "Visited"),
                            ("completed", "Completed"),
                            ("follow_up", "Follow-up"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                ("lost_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="core.department",
                    ),
                ),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="enquiries.enquiry",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
