# Generated by Django 5.0.14 on 2026-08-12 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("enquiries", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="enquirystagechange",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enquirystagechange",
            name="enquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_changes",
                to="enquiries.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="enquirystagechange",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.hospital",
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["hospital", "stage", "created_at"],
                name="enquiries_e_hospita_0b66d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enquiry",
            index=models.Index(
                fields=["hospital", "mobile"], name="enquiries_e_hospita_803d7f_idx"
            ),
        ),
    ]
