# Generated by Django 5.0.14 on 2026-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
