# Generated by Django 5.2.17 on 2026-08-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospital_lead_webhook_token"),
        ("enquiries", "0003_enquiry_estimated_value"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="landing_page",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="lost_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="referrer_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_content",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="utm_term",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="lost_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cost", "Cost too high"),
                    ("location", "Location inconvenient"),
                    ("went_elsewhere", "Chose another hospital"),
                    ("no_response", "Could not be reached"),
                    ("not_interested", "No longer interested"),
                    ("medical_reason", "Medical reason changed"),
                    ("duplicate", "Duplicate / test enquiry"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="EnquiryAssignmentChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_changes",
                        to="enquiries.enquiry",
                    ),
                ),
                (
                    "from_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "to_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
