# Generated by Django 5.2.17 on 2026-09-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctor_user'),
        ('core', '0009_alter_auditlog_action'),
        ('enquiries', '0004_lead_management_enhancements'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_name', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('room_category', models.CharField(choices=[('general', 'General Ward'), ('semi_private', 'Semi-Private'), ('private', 'Private Room (AC)'), ('deluxe', 'Deluxe Suite')], default='semi_private', max_length=20)),
                ('stay_days', models.PositiveSmallIntegerField(default=2)),
                ('surgeon_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ot_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('room_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('medicines_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('implants_investigations', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Self Pay / Cash'), ('insurance', 'Private Insurance (Cashless)'), ('govt_scheme', 'Ayushman / CGHS / Govt'), ('corporate', 'Corporate TPA')], default='insurance', max_length=20)),
                ('tpa_name', models.CharField(blank=True, max_length=150)),
                ('insurance_preauth_status', models.CharField(choices=[('not_applicable', 'Not Applicable (Cash)'), ('pending_docs', 'Documents Pending'), ('submitted', 'Submitted to TPA'), ('query_raised', 'Query Raised by TPA'), ('approved', 'Pre-Auth Approved'), ('denied', 'Pre-Auth Denied')], default='not_applicable', max_length=20)),
                ('approved_preauth_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stage', models.CharField(choices=[('advised', 'Advised by Doctor'), ('counseling', 'Financial Counseling'), ('estimate_shared', 'Estimate Shared'), ('preauth_in_progress', 'Insurance Pre-Auth'), ('scheduled', 'Surgery Scheduled'), ('converted', 'Admitted / Converted'), ('dropped', 'Dropped / Lost')], default='advised', max_length=24)),
                ('drop_reason', models.CharField(blank=True, choices=[('cost_high', 'Cost too high'), ('fear', 'Patient hesitation / fear'), ('went_elsewhere', 'Chose competitor hospital'), ('postponed', 'Postponed indefinitely'), ('insurance_rejected', 'Insurance pre-auth rejected'), ('other', 'Other')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_estimates', to='core.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_estimates', to='appointments.doctor')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_estimates', to='enquiries.enquiry')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_estimates', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'stage', 'created_at'], name='enquiries_t_hospita_4bb268_idx')],
            },
        ),
    ]
