# Generated by Django 5.2.17 on 2026-09-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctor_user'),
        ('enquiries', '0005_treatmentestimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='consulting_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who consulted / is scheduled with this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='appointments.doctor'),
        ),
    ]
