# Generated by Django 5.2.17 on 2026-09-12 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctor_user'),
        ('core', '0009_alter_auditlog_action'),
        ('enquiries', '0006_add_consulting_doctor'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Scheduled callback / follow-up date', null=True),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['hospital', 'follow_up_date'], name='enquiries_e_hospita_0d4117_idx'),
        ),
    ]
