# Generated by Django 5.2.17 on 2026-08-14 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='source_ed_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_admissions', to='emergency.edvisit'),
        ),
    ]
