# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_doctor_user'),
        ('core', '0007_alter_hospital_slug'),
        ('emergency', '0001_initial'),
        ('facilities', '0002_bed_current_admission'),
        ('ipd', '0002_admission_source_ed_visit'),
        ('opd', '0001_initial'),
        ('patients', '0011_prescription_encounter'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['hospital', 'status'], name='ipd_admissi_hospita_a6eaf4_idx'),
        ),
    ]
