# Generated by Django 5.2.17 on 2026-09-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('ipd', '0003_admission_ipd_admissi_hospita_a6eaf4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='clinical.episodeofcare'),
        ),
    ]
