# Generated by Django 5.2.17 on 2026-09-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctor_user'),
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0004_admission_episode'),
        ('packages', '0002_crm_gap_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='admission',
            name='care_team',
            field=models.ManyToManyField(blank=True, related_name='care_team_admissions', to='appointments.doctor'),
        ),
        migrations.AddField(
            model_name='admission',
            name='discharge_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='expected_discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='packages.healthpackage'),
        ),
        migrations.CreateModel(
            name='AdmissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_type', models.CharField(choices=[('planned', 'Planned'), ('emergency', 'Emergency')], max_length=16)),
                ('checklist_items', models.JSONField(default=list, help_text='["Consent signed", "Deposit collected", "ID proof verified", ...]')),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_consent', models.BooleanField(default=True)),
                ('notify_departments', models.JSONField(default=list, help_text='["nursing", "dietary", "billing", "pharmacy"] alerted on admission/transfer.')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DischargeClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('nursing', 'Nursing'), ('pharmacy', 'Pharmacy (returns)'), ('laboratory', 'Laboratory'), ('radiology', 'Radiology'), ('dietary', 'Dietary'), ('billing', 'Billing / accounts'), ('tpa', 'TPA / insurance'), ('medical_records', 'Medical records')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('na', 'Not applicable')], default='pending', max_length=8)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='ipd.admission')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['department'],
                'constraints': [models.UniqueConstraint(fields=('admission', 'department'), name='unique_clearance_per_department')],
            },
        ),
    ]
