# Generated by Django 5.2.17 on 2026-09-23 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0004_admission_episode'),
        ('ot', '0002_alter_anaesthesiarecord_options_and_more'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntimicrobialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug', models.CharField(max_length=150)),
                ('indication', models.TextField()),
                ('culture_sent', models.BooleanField(default=False)),
                ('culture_report', models.TextField(blank=True)),
                ('planned_duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antimicrobial_approvals', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.prescription')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AntimicrobialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Antimicrobial Usage Policy', max_length=200)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('sections', models.JSONField(default=list)),
                ('document', models.FileField(blank=True, upload_to='policies/')),
                ('is_current', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'verbose_name_plural': 'antimicrobial policies',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='DeviceEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.CharField(choices=[('urinary_catheter', 'Indwelling urinary catheter'), ('central_line', 'Central line'), ('ventilator', 'Ventilator'), ('peripheral_iv', 'Peripheral IV')], max_length=20)),
                ('site', models.CharField(blank=True, max_length=80)),
                ('inserted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('bundle_compliance', models.JSONField(blank=True, default=dict, help_text='Insertion/maintenance bundle checklist answers.')),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_episodes', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_episodes', to='patients.patient')),
            ],
            options={
                'ordering': ['-inserted_at'],
            },
        ),
        migrations.CreateModel(
            name='HAIIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infection_type', models.CharField(choices=[('cauti', 'CAUTI'), ('clabsi', 'CLABSI'), ('vap', 'VAP'), ('ssi', 'Surgical site infection'), ('mrsa', 'MRSA / MDRO colonisation'), ('cdi', 'C. difficile'), ('gastroenteritis', 'Gastroenteritis'), ('other', 'Other HAI')], max_length=16)),
                ('ward', models.CharField(blank=True, max_length=80)),
                ('onset_date', models.DateField(default=django.utils.timezone.localdate)),
                ('organism', models.CharField(blank=True, max_length=150)),
                ('sensitivity_pattern', models.TextField(blank=True)),
                ('is_mdro', models.BooleanField(default=False)),
                ('isolation_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('suspected', 'Suspected'), ('confirmed', 'Confirmed'), ('ruled_out', 'Ruled out'), ('resolved', 'Resolved')], default='suspected', max_length=10)),
                ('actions_taken', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hai_incidents', to='ipd.admission')),
                ('device_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infections', to='infection_control.deviceepisode')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hai_incidents', to='patients.patient')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infections', to='ot.surgeryrequest')),
            ],
            options={
                'ordering': ['-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='HandHygieneAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('ward', models.CharField(max_length=80)),
                ('staff_category', models.CharField(blank=True, help_text='doctor / nurse / technician / housekeeping', max_length=40)),
                ('opportunities', models.PositiveIntegerField()),
                ('compliant', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exposure_type', models.CharField(choices=[('needlestick', 'Needlestick / sharps injury'), ('splash', 'Blood/body-fluid splash'), ('airborne', 'Airborne (TB etc.)'), ('other', 'Other')], max_length=12)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('source_status', models.JSONField(blank=True, default=dict, help_text='{"hiv": "neg", "hbsag": "pos", "hcv": "unknown"}')),
                ('staff_hbv_vaccinated', models.BooleanField(default=False)),
                ('first_aid_given', models.BooleanField(default=True)),
                ('pep_given', models.BooleanField(default=False)),
                ('pep_details', models.TextField(blank=True)),
                ('pep_started_at', models.DateTimeField(blank=True, null=True)),
                ('followups', models.JSONField(blank=True, default=list, help_text='[{due: date, done: bool, result: str}] — 6 wk / 3 mo / 6 mo tests.')),
                ('status', models.CharField(choices=[('open', 'Under follow-up'), ('closed', 'Closed — no seroconversion'), ('seroconverted', 'Seroconverted')], default='open', max_length=14)),
                ('description', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
