# Generated by Django 5.0.14 on 2026-08-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_hospital_google_review_url_and_more'),
        ('patients', '0002_patient_attendant_name_patient_attendant_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferringDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.CharField(blank=True, max_length=150)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(default='Pune', max_length=100)),
                ('tier', models.CharField(choices=[('gold', 'Gold Tier'), ('silver', 'Silver Tier'), ('bronze', 'Bronze Tier')], default='silver', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Visit'), ('converted', 'OPD/IPD Converted'), ('paid', 'Statement Settled')], default='pending', max_length=16)),
                ('referred_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_records', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referringdoctor')),
            ],
            options={
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField()),
                ('notes', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('visited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_visits', to='referrals.referringdoctor')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
