# Generated by Django 5.2.17 on 2026-09-11 12:03

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_hospital_grievance_officer_email_and_more"),
        ("patients", "0014_alter_patient_insurance_policy_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False, editable=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "delete_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "relationship",
                    models.CharField(
                        help_text="e.g. spouse, child, parent", max_length=100
                    ),
                ),
                (
                    "phone",
                    apps.core.fields.EncryptedCharField(blank=True, max_length=20),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="patients.patient",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRightsRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "Access my data"),
                            ("correction", "Correct my data"),
                            ("erasure", "Erase my data"),
                            ("nomination", "Nominate someone to act for me"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("verified", "Identity verified"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("written", "Written / in-person"),
                            ("portal", "Patient portal"),
                        ],
                        default="phone",
                        max_length=16,
                    ),
                ),
                ("details", apps.core.fields.EncryptedTextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("sla_due_at", models.DateTimeField(editable=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", apps.core.fields.EncryptedTextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_rights_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["hospital", "status"],
                        name="privacy_dat_hospita_b88e2a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GrievanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("description", apps.core.fields.EncryptedTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("sla_due_at", models.DateTimeField(editable=False)),
                ("resolution", apps.core.fields.EncryptedTextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grievance_tickets",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["hospital", "status"],
                        name="privacy_gri_hospita_bb56c3_idx",
                    )
                ],
            },
        ),
    ]
