# Generated by Django 5.2.17 on 2026-08-14 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('ward_type', models.CharField(choices=[('general', 'General'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU'), ('ot_prep', 'OT Prep/Recovery')], default='general', max_length=16)),
                ('floor', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=32)),
                ('room_type', models.CharField(choices=[('general', 'General'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('deluxe', 'Deluxe')], default='general', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='facilities.ward')),
            ],
            options={
                'ordering': ['ward__name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed_number', models.CharField(max_length=32)),
                ('bed_type', models.CharField(choices=[('general', 'General'), ('semi_private', 'Semi-Private'), ('private', 'Private'), ('icu', 'ICU'), ('ventilator', 'Ventilator')], default='general', max_length=16)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=16)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='facilities.room')),
            ],
            options={
                'ordering': ['room__ward__name', 'room__room_number', 'bed_number'],
                'constraints': [models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_bed_number_per_room')],
            },
        ),
        migrations.AddConstraint(
            model_name='ward',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_ward_name_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('ward', 'room_number'), name='unique_room_number_per_ward'),
        ),
    ]
