# Generated by Django 5.2.17 on 2026-08-14 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='current_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipd.admission'),
        ),
    ]
