# Generated by Django 5.2.17 on 2026-10-01 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_bed_status'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='reserved_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_beds', to='patients.patient'),
        ),
    ]
