# Generated by Django 5.2.17 on 2026-08-14 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
        ('patients', '0011_prescription_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('triaged', 'Triaged'), ('in_treatment', 'In Treatment'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('referred_out', 'Referred Out'), ('deceased', 'Deceased')], default='triaged', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triage_category', models.CharField(choices=[('1_resuscitation', 'Category 1 - Resuscitation'), ('2_emergent', 'Category 2 - Emergent'), ('3_urgent', 'Category 3 - Urgent'), ('4_less_urgent', 'Category 4 - Less Urgent'), ('5_non_urgent', 'Category 5 - Non Urgent')], max_length=32)),
                ('vitals_summary', models.TextField(blank=True)),
                ('triaged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ed_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='emergency.edvisit')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
