# Generated by Django 5.2.17 on 2026-09-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        ('support_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edvisit',
            name='ambulance_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ed_visits', to='support_services.ambulancetrip'),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='brought_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='disposition_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='injuries_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='is_mlc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='is_unidentified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mlc_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mlc_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mlc_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mlc_number',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mlc_type',
            field=models.CharField(blank=True, help_text='RTA | assault | burns | poisoning | fall | hanging | sexual_assault | other', max_length=40),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='mode_of_arrival',
            field=models.CharField(blank=True, help_text='walk_in | ambulance | referred | police', max_length=20),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='police_intimated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='police_officer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='edvisit',
            name='police_station',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
