# Generated by Django 5.2.17 on 2026-09-23 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('feature', 'Feature'), ('bugfix', 'Bug fix'), ('security', 'Security patch')], default='feature', max_length=16)),
                ('released_on', models.DateField(default=django.utils.timezone.localdate)),
                ('summary', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-released_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. NABH Full Accreditation', max_length=200)),
                ('issuing_body', models.CharField(default='NABH', max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='accreditations/')),
                ('show_on_login', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('model_name', models.CharField(default='*', max_length=100)),
                ('actions', models.JSONField(default=list, help_text='Subset of ["create","update","delete","read","request","export"]; empty = all.')),
                ('capture_reads', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=2555, help_text='≈7 years by default.')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired & purged'), ('restored', 'Restored')], default='running', max_length=16)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('guide', 'User guide'), ('faq', 'FAQ'), ('tutorial', 'Tutorial'), ('troubleshooting', 'Troubleshooting'), ('policy', 'Policy / SOP')], default='guide', max_length=20)),
                ('module', models.CharField(blank=True, help_text='e.g. opd, laboratory, billing', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_articles', to='core.hospital')),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_retention_days', models.PositiveIntegerField(default=1825, help_text='Backups older than this are deleted (default 5 years).')),
                ('auto_backup_enabled', models.BooleanField(default=True)),
                ('auto_backup_frequency_hours', models.PositiveSmallIntegerField(default=24)),
                ('archive_audit_logs_after_days', models.PositiveIntegerField(default=2555)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_min_length', models.PositiveSmallIntegerField(default=10)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_digit', models.BooleanField(default=True)),
                ('password_require_symbol', models.BooleanField(default=True)),
                ('password_expiry_days', models.PositiveSmallIntegerField(default=90, help_text='0 = never expires.')),
                ('password_history_count', models.PositiveSmallIntegerField(default=5, help_text='Reject reuse of the last N passwords.')),
                ('lockout_threshold', models.PositiveSmallIntegerField(default=5, help_text='Failed logins before the account locks. 0 = never lock.')),
                ('lockout_minutes', models.PositiveSmallIntegerField(default=30)),
                ('idle_lock_enabled', models.BooleanField(default=True)),
                ('idle_lock_minutes', models.PositiveSmallIntegerField(default=10)),
                ('enforce_mfa_for_all', models.BooleanField(default=False, help_text='Require MFA for every user, not only owner/admin roles.')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('locked_login_attempt', 'Login attempt on locked account'), ('password_changed', 'Password changed'), ('password_expired', 'Password expired'), ('mfa_failed', 'MFA verification failed'), ('access_denied', 'Unauthorized access attempt'), ('ip_blocked', 'Login from disallowed network'), ('screen_unlock_failed', 'Screen unlock failed'), ('data_export', 'Bulk data export'), ('backup', 'Backup'), ('rollback', 'Change rolled back'), ('policy_changed', 'Security policy changed')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='core.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hospital', 'event_type', 'created_at'], name='governance__hospita_aebd75_idx')],
            },
        ),
    ]
