# Generated by Django 5.2.17 on 2026-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypolicy',
            name='sso_required',
            field=models.BooleanField(default=False, help_text="Staff must sign in through the hospital's SSO provider."),
        ),
    ]
