# Generated by Django 5.2.17 on 2026-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0004_permission_ceiling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('account_locked', 'Account locked'), ('account_unlocked', 'Account unlocked'), ('user_blocked', 'User blocked'), ('user_unblocked', 'User unblocked'), ('locked_login_attempt', 'Login attempt on locked account'), ('password_changed', 'Password changed'), ('password_expired', 'Password expired'), ('mfa_failed', 'MFA verification failed'), ('access_denied', 'Unauthorized access attempt'), ('ip_blocked', 'Login from disallowed network'), ('screen_unlock_failed', 'Screen unlock failed'), ('data_export', 'Bulk data export'), ('backup', 'Backup'), ('rollback', 'Change rolled back'), ('policy_changed', 'Security policy changed'), ('support_access', 'Platform support access'), ('saas_access_changed', 'SaaS account access changed'), ('permissions_changed', 'Permissions changed'), ('license_issued', 'Licence requested, approved, issued or revoked'), ('license_alert', 'Licence security alert')], max_length=32),
        ),
    ]
