# Generated by Django 5.0.14 on 2026-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='template',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('doctor', 'OPD Doctor'), ('front_desk', 'Front Desk'), ('telephony_operator', 'Telephony Operator')], help_text='Applies a starter permission set on creation only — see apps.accounts.permission_templates. Leave blank for a hand-built role with no default permissions.', max_length=32),
        ),
    ]
