# Generated by Django 5.2.17 on 2026-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('all', 'All hospital records'), ('assigned_only', 'Assigned records only')], default='all', help_text='assigned_only narrows any ViewSet declaring assignment_scope_field (see apps.core.viewsets.TenantScopedViewSetMixin) to records assigned to the requesting user.', max_length=16),
        ),
        migrations.AddField(
            model_name='role',
            name='domain',
            field=models.CharField(choices=[('crm', 'CRM'), ('erp', 'ERP'), ('both', 'Both')], default='both', help_text='Drives which top-level nav (CRM/ERP/both) the frontend shows for users with this role — see docs/erp/06-navigation-and-dashboards.md.', max_length=8),
        ),
        migrations.AlterField(
            model_name='role',
            name='template',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('doctor', 'OPD Doctor'), ('front_desk', 'Front Desk'), ('telephony_operator', 'Telephony Operator'), ('crm_super_admin', 'CRM Super Admin'), ('crm_manager', 'CRM Manager'), ('crm_executive', 'CRM Executive'), ('call_centre_executive', 'Call Centre Executive'), ('marketing_manager', 'Marketing Manager'), ('corporate_rm', 'Corporate Relationship Manager'), ('crm_auditor', 'CRM Auditor')], help_text='Applies a starter permission set on creation only — see apps.accounts.permission_templates. Leave blank for a hand-built role with no default permissions.', max_length=32),
        ),
    ]
