# Generated by Django 5.2.17 on 2026-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_role_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='template',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('doctor', 'OPD Doctor'), ('front_desk', 'Front Desk'), ('telephony_operator', 'Telephony Operator'), ('crm_super_admin', 'CRM Super Admin'), ('crm_manager', 'CRM Manager'), ('crm_executive', 'CRM Executive'), ('call_centre_executive', 'Call Centre Executive'), ('marketing_manager', 'Marketing Manager'), ('corporate_rm', 'Corporate Relationship Manager'), ('crm_auditor', 'CRM Auditor'), ('receptionist', 'Receptionist / ERP Front Desk'), ('hospital_administrator', 'Hospital Administrator'), ('nurse', 'Nurse'), ('lab_technician', 'Lab Technician'), ('lab_manager', 'Lab Pathologist / Manager'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('ot_manager', 'OT Manager'), ('surgeon', 'Surgeon'), ('anaesthetist', 'Anaesthetist'), ('icu_staff', 'ICU Staff'), ('finance_manager', 'Finance Manager'), ('hr_manager', 'HR Manager'), ('him_officer', 'HIM Officer'), ('hospital_auditor', 'Hospital Auditor'), ('billing_executive', 'Billing Executive'), ('billing_manager', 'Billing Manager'), ('insurance_tpa_executive', 'Insurance / TPA Executive'), ('inventory_manager', 'Inventory Manager'), ('purchase_manager', 'Purchase Manager')], help_text='Applies a starter permission set on creation only — see apps.accounts.permission_templates. Leave blank for a hand-built role with no default permissions.', max_length=32),
        ),
    ]
