# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_role_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_saas_admin',
            field=models.BooleanField(default=False, help_text="Master SaaS Admin / platform owner — manages tenants, subscriptions, billing, and support tickets across every hospital (apps.saas_admin, apps.core.permissions.IsSaaSAdmin). Narrower than is_staff (which every SaaS admin also gets — see save() below): plenty of is_staff platform-ops accounts don't need to see cross-tenant billing/revenue data."),
        ),
    ]
