# Generated by Django 5.2.17 on 2026-09-11 04:07

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_role_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=apps.core.fields.EncryptedCharField(
                blank=True, editable=False, max_length=64
            ),
        ),
    ]
