# Generated by Django 5.2.17 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Administratively blocked — cannot sign in until unblocked.'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Medical/nursing council registration number, printed with the signature.', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Digital signature stamped on signed clinical documents (COP.1.e).', upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('all', 'All hospital records'), ('assigned_only', 'Assigned records only')], default='all', help_text='assigned_only narrows any ViewSet declaring assignment_scope_field to records assigned to the requesting user.', max_length=16),
        ),
        migrations.AlterField(
            model_name='role',
            name='domain',
            field=models.CharField(choices=[('crm', 'CRM'), ('erp', 'ERP'), ('both', 'Both')], default='both', help_text='Drives which top-level nav (CRM/ERP/both) the frontend shows for users with this role.', max_length=8),
        ),
        migrations.AlterField(
            model_name='role',
            name='template',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('doctor', 'OPD Doctor'), ('front_desk', 'Front Desk'), ('telephony_operator', 'Telephony Operator'), ('crm_super_admin', 'CRM Super Admin'), ('crm_manager', 'CRM Manager'), ('crm_executive', 'CRM Executive'), ('call_centre_executive', 'Call Centre Executive'), ('marketing_manager', 'Marketing Manager'), ('corporate_rm', 'Corporate Relationship Manager'), ('crm_auditor', 'CRM Auditor'), ('receptionist', 'Receptionist / ERP Front Desk'), ('hospital_administrator', 'Hospital Administrator'), ('nurse', 'Nurse'), ('lab_technician', 'Lab Technician'), ('lab_manager', 'Lab Pathologist / Manager'), ('radiology_technician', 'Radiology Technician'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('ot_manager', 'OT Manager'), ('surgeon', 'Surgeon'), ('anaesthetist', 'Anaesthetist'), ('icu_staff', 'ICU Staff'), ('blood_bank_technician', 'Blood Bank Technician'), ('finance_manager', 'Finance Manager'), ('hr_manager', 'HR Manager'), ('him_officer', 'HIM Officer'), ('hospital_auditor', 'Hospital Auditor'), ('billing_executive', 'Billing Executive'), ('billing_manager', 'Billing Manager'), ('insurance_tpa_executive', 'Insurance / TPA Executive'), ('inventory_manager', 'Inventory Manager'), ('purchase_manager', 'Purchase Manager')], help_text='Applies a starter permission set on creation only.', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_saas_admin',
            field=models.BooleanField(default=False, help_text='Master SaaS Admin / platform owner — manages tenants, subscriptions, billing, and support tickets across every hospital.'),
        ),
    ]
