# Generated by Django 5.2.17 on 2026-09-24 09:41

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_blocked_reason_user_failed_login_attempts_and_more'),
        ('core', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('microsoft', 'Microsoft Entra ID (Microsoft 365)'), ('google', 'Google Workspace'), ('oidc', 'Other OpenID Connect provider')], max_length=10)),
                ('display_name', models.CharField(help_text='Shown on the login button, e.g. "Microsoft"', max_length=80)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', apps.core.fields.EncryptedTextField()),
                ('tenant_id', models.CharField(blank=True, help_text='Microsoft: your directory (tenant) ID — required', max_length=64)),
                ('discovery_url', models.URLField(blank=True, help_text='Other OIDC providers: the .well-known/openid-configuration URL')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text='Only emails at these domains may sign in, e.g. ["cityhospital.in"]')),
                ('is_enabled', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='SSOLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('nonce', models.CharField(max_length=64)),
                ('code_verifier', models.CharField(max_length=128)),
                ('return_to', models.URLField()),
                ('next_path', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_code_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('exchanged_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.ssoprovider')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='accounts_ss_created_0866b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('email_at_link', models.EmailField(max_length=254)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identities', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='accounts.ssoprovider')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_sso_subject_per_provider'), models.UniqueConstraint(fields=('provider', 'user'), name='one_sso_identity_per_user_per_provider')],
            },
        ),
    ]
