# Generated by Django 5.2.17 on 2026-09-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='template_synced_models',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
