# Generated by Django 5.2.17 on 2026-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_grant_view_for_read_enforcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_issue_licenses',
            field=models.BooleanField(default=False, help_text='Polynexus staff: may request on-premise licences (a SaaS Owner approves them). Granted only by a SaaS Owner.'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_code',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
