# Generated by Django 5.0.14 on 2026-08-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_hospital_google_review_url_and_more'),
        ('patients', '0002_patient_attendant_name_patient_attendant_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPACompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=32)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('claim_submission_email', models.EmailField(blank=True, max_length=254)),
                ('avg_tat_days', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PreAuthRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(max_length=100)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('submitted', 'Pre-Auth Submitted'), ('query_raised', 'Insurer Query Raised'), ('approved', 'Pre-Auth Approved'), ('rejected', 'Pre-Auth Rejected')], default='submitted', max_length=24)),
                ('checklist', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preauth_requests', to='patients.patient')),
                ('tpa_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preauth_requests', to='tpa.tpacompany')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
