# Generated by Django 5.2.17 on 2026-08-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospital_lead_webhook_token"),
        ("patients", "0004_crm_gap_fixes"),
        ("tpa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_number", models.CharField(blank=True, max_length=100)),
                ("billed_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "settled_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Claim Submitted"),
                            ("under_review", "Under Review"),
                            ("settled", "Settled"),
                            ("partially_settled", "Partially Settled"),
                            ("rejected", "Rejected"),
                        ],
                        default="submitted",
                        max_length=24,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="patients.patient",
                    ),
                ),
                (
                    "preauth_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="tpa.preauthrequest",
                    ),
                ),
                (
                    "tpa_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="tpa.tpacompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
