# Generated by Django 5.2.17 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0002_crm_gap_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthrequest',
            name='policy_number_lookup',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='preauthrequest',
            name='policy_number',
            field=models.TextField(),
        ),
    ]
