# Generated by Django 5.2.17 on 2026-08-14 07:13

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0004_encrypt_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preauthrequest',
            name='policy_number',
            field=apps.core.encryption.EncryptedTextField(),
        ),
    ]
