# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospital_slug'),
        ('patients', '0011_prescription_encounter'),
        ('tpa', '0005_switch_policy_number_to_encrypted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['hospital', 'status'], name='tpa_claim_hospita_8b1265_idx'),
        ),
    ]
