# Generated by Django 5.2.17 on 2026-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icudailyprogressnote',
            options={'ordering': ['-created_at'], 'permissions': [('finalize_icudailyprogressnote', 'Can finalize an ICU daily progress note')]},
        ),
    ]
