# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospital_slug'),
        ('facilities', '0002_bed_current_admission'),
        ('icu', '0002_alter_icudailyprogressnote_options'),
        ('ipd', '0002_admission_source_ed_visit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='icuadmission',
            index=models.Index(fields=['hospital', 'discharged_at'], name='icu_icuadmi_hospita_bdf47b_idx'),
        ),
    ]
