# Generated by Django 5.2.17 on 2026-09-23 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('icu', '0003_icuadmission_icu_icuadmi_hospita_bdf47b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icuadmission',
            name='admission_criteria_met',
            field=models.JSONField(blank=True, default=list, help_text='Codes of ICUCriterion rows (kind=admission) met.'),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='discharge_criteria_met',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='is_eligible',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='is_readmission_48h',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='outcome',
            field=models.CharField(blank=True, choices=[('ward', 'Shifted to ward'), ('transferred', 'Transferred out'), ('dama', 'Discharged against advice'), ('death', 'Death')], max_length=12),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='predicted_mortality',
            field=models.DecimalField(blank=True, decimal_places=1, editable=False, help_text='%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='severity_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='severity_scale',
            field=models.CharField(blank=True, help_text='apache_ii | sofa', max_length=12),
        ),
        migrations.AddField(
            model_name='icuadmission',
            name='severity_score',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='CareBundleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.CharField(max_length=20)),
                ('elements', models.JSONField(default=dict)),
                ('compliant', models.BooleanField(default=False, editable=False)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('icu_admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_logs', to='icu.icuadmission')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='ICUCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('admission', 'Admission'), ('discharge', 'Discharge')], max_length=10)),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['kind', 'code'],
            },
        ),
    ]
