# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0007_alter_hospital_slug'),
        ('ipd', '0002_admission_source_ed_visit'),
        ('patients', '0011_prescription_encounter'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['hospital', 'status'], name='billing_bil_hospita_526e33_idx'),
        ),
    ]
