# Generated by Django 5.2.17 on 2026-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_billing_bil_hospita_526e33_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_interim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_category',
            field=models.CharField(default='general', help_text='general | private | insurance | corporate', max_length=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='billitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
