# Generated by Django 5.2.17 on 2026-09-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_bill_bill_number_bill_is_interim_and_more'),
        ('finance', '0003_claimsettlement_insurancepolicy_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.servicetariff'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('wallet', 'Wallet'), ('insurance', 'Insurance / TPA settlement'), ('advance', 'Adjusted from deposit')], default='cash', max_length=20),
        ),
    ]
