# Generated by Django 5.2.17 on 2026-09-24 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_consult_started_at_and_more'),
        ('billing', '0004_billitem_tariff_billitem_tax_amount_and_more'),
        ('core', '0009_alter_auditlog_action'),
        ('facilities', '0003_alter_bed_status'),
        ('finance', '0003_claimsettlement_insurancepolicy_journalentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='appointments.doctor'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='source_ref',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='BedChargeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('bed_type', models.CharField(blank=True, help_text='facilities.Bed.BedType value; blank = any', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.servicetariff')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='facilities.ward')),
            ],
            options={
                'ordering': ['ward__name', 'bed_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BedBillingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.CharField(choices=[('24h', '24-hour cycle from admission time'), ('calendar_day', 'Calendar day (discharge day charged only after checkout hour)')], default='24h', max_length=16)),
                ('grace_hours', models.PositiveSmallIntegerField(default=2, help_text='24h cycle: hours into a new cycle before it is charged.')),
                ('checkout_hour', models.PositiveSmallIntegerField(default=12, help_text='Calendar day: discharge after this hour charges the discharge day too.')),
                ('transfer_day_rule', models.CharField(choices=[('higher', 'Charge the higher-rate bed for the day'), ('longest', 'Charge the bed occupied longest that day')], default='higher', max_length=10)),
                ('auto_post', models.BooleanField(default=True, help_text='Post bed charges nightly and at discharge.')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hospital',), name='one_bed_billing_policy_per_hospital')],
            },
        ),
    ]
