# Generated by Django 5.0.14 on 2026-08-12 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_hospital_google_review_url_and_more"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HISBillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_bill_id", models.CharField(max_length=128)),
                ("bill_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("partial", "Partially paid"),
                            ("outstanding", "Outstanding"),
                        ],
                        max_length=16,
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="his_billing_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date"],
            },
        ),
        migrations.CreateModel(
            name="HISVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_visit_id", models.CharField(max_length=128)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("opd", "OPD"),
                            ("ipd", "IPD"),
                            ("diagnostic", "Diagnostic"),
                        ],
                        max_length=16,
                    ),
                ),
                ("visit_date", models.DateTimeField()),
                ("department_name", models.CharField(blank=True, max_length=150)),
                ("doctor_name", models.CharField(blank=True, max_length=150)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="his_visits",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="hisbillingrecord",
            constraint=models.UniqueConstraint(
                fields=("hospital", "external_bill_id"),
                name="unique_his_bill_per_hospital",
            ),
        ),
        migrations.AddConstraint(
            model_name="hisvisit",
            constraint=models.UniqueConstraint(
                fields=("hospital", "external_visit_id"),
                name="unique_his_visit_per_hospital",
            ),
        ),
    ]
