# Generated by Django 5.2.17 on 2026-09-24 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('finance', '0002_alter_expense_expense_date'),
        ('inventory', '0001_initial'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        ('tpa', '0006_claim_tpa_claim_hospita_8b1265_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utr_number', models.CharField(max_length=40)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disallowed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disallowance_reasons', models.TextField(blank=True)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_reconciled', models.BooleanField(default=False, editable=False)),
                ('response_to_payer', models.TextField(blank=True, help_text='Query reply / dispute of disallowances.')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='tpa.claim')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-received_on'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.CharField(max_length=150)),
                ('scheme', models.CharField(blank=True, help_text='e.g. PM-JAY, CGHS, corporate group policy', max_length=100)),
                ('policy_number', models.CharField(max_length=80)),
                ('member_id', models.CharField(blank=True, max_length=80)),
                ('sum_insured', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_available', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('coverage_notes', models.TextField(blank=True, help_text='Room-rent cap, co-pay, exclusions')),
                ('eligibility_status', models.CharField(default='unverified', help_text='unverified | eligible | ineligible', max_length=12)),
                ('eligibility_checked_at', models.DateTimeField(blank=True, null=True)),
                ('card_image', models.FileField(blank=True, upload_to='insurance_cards/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient')),
                ('tpa_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tpa.tpacompany')),
            ],
            options={
                'ordering': ['-valid_to'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_type', models.CharField(choices=[('sales', 'Sales'), ('receipt', 'Receipt'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('journal', 'Journal'), ('debit_note', 'Debit note'), ('credit_note', 'Credit note')], max_length=12)),
                ('voucher_number', models.CharField(max_length=40)),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=40)),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('exported_to_tally_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=10)),
                ('tally_group', models.CharField(blank=True, help_text='Tally parent group, e.g. Sundry Debtors, Sales Accounts.', max_length=60)),
                ('is_system', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.ledgeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_rates', models.JSONField(blank=True, default=dict)),
                ('hsn_sac', models.CharField(blank=True, help_text='SAC 9993 for healthcare services; HSN for goods.', max_length=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('state_code', models.CharField(blank=True, help_text='GST state code, e.g. 27 = Maharashtra', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credit_days', models.PositiveSmallIntegerField(default=30, help_text='FPM.2.e payment terms for this supplier.')),
                ('bank_account', models.CharField(blank=True, max_length=40)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=60)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('matched', '3-way matched'), ('mismatch', 'Mismatch (on hold)'), ('approved', 'Approved for payment'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='received', max_length=16)),
                ('match_notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_invoices', to='inventory.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.vendor')),
            ],
            options={
                'ordering': ['due_date', '-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('debit', 'Debit note (we claim from supplier)'), ('credit', 'Credit note (supplier credits us)')], max_length=6)),
                ('note_number', models.CharField(blank=True, editable=False, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='finance.vendor')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='finance.vendorinvoice')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode', models.CharField(choices=[('neft', 'NEFT / RTGS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='neft', max_length=8)),
                ('reference', models.CharField(blank=True, help_text='UTR / cheque number', max_length=60)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor_notified_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.vendorinvoice')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on'],
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('hospital', 'source_type', 'source_id', 'voucher_type'), name='one_voucher_per_source'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_ledger_account_code'),
        ),
        migrations.AddConstraint(
            model_name='servicetariff',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_tariff_code'),
        ),
        migrations.AddConstraint(
            model_name='vendorinvoice',
            constraint=models.UniqueConstraint(fields=('hospital', 'vendor', 'invoice_number'), name='unique_vendor_invoice'),
        ),
    ]
