# Generated by Django 5.2.17 on 2026-09-24 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_consult_started_at_and_more'),
        ('billing', '0005_bed_charges_and_item_attribution'),
        ('core', '0009_alter_auditlog_action'),
        ('finance', '0003_claimsettlement_insurancepolicy_journalentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, help_text='Net billed value of the services', max_digits=14)),
                ('gross_payout', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_percent', models.DecimalField(decimal_places=2, default=10, help_text='Sec 194J professional fees', max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, help_text='neft | upi | cheque | cash', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='appointments.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-period_end', 'doctor__name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPayoutRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('service_department', models.CharField(blank=True, help_text="ServiceTariff.department, e.g. 'Radiology'", max_length=60)),
                ('patient_category', models.CharField(blank=True, help_text='general | private | insurance | corporate; blank = any', max_length=12)),
                ('basis', models.CharField(choices=[('percent', '% of net amount (after discount, before GST)'), ('fixed', 'Fixed amount per unit')], default='percent', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_on', models.CharField(choices=[('billed', 'When billed'), ('collected', 'When the bill is fully paid')], default='billed', max_length=10)),
                ('priority', models.SmallIntegerField(default=0)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_rules', to='appointments.doctor')),
                ('doctor_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.servicetariff')),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_label', models.CharField(max_length=200)),
                ('bill_number', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('service_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_line', to='billing.billitem')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.doctorpayout')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.doctorpayoutrule')),
            ],
            options={
                'ordering': ['service_date', 'id'],
            },
        ),
    ]
