# Generated by Django 5.2.17 on 2026-08-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
        ('opd', '0001_initial'),
        ('patients', '0011_prescription_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('resulted', 'Resulted'), ('verified', 'Verified')], default='ordered', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('investigation_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='opd.investigationorder')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('department', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('pathology', 'Pathology'), ('other', 'Other')], default='other', max_length=16)),
                ('reference_range', models.CharField(blank=True, help_text="e.g. '70-100 mg/dL' — free text, not parsed.", max_length=255)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('reference_range', models.CharField(blank=True, max_length=255)),
                ('flag', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critical', 'Critical')], default='normal', max_length=16)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborder')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('verify_labresult', 'Can verify (finalize) a lab result')],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordered_tests',
            field=models.ManyToManyField(blank=True, related_name='orders', to='laboratory.labtest'),
        ),
        migrations.CreateModel(
            name='LabTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('tests', models.ManyToManyField(blank=True, related_name='packages', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_type', models.CharField(help_text='e.g. Blood, Urine, Swab', max_length=100)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_collections', to='laboratory.laborder')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
