# Generated by Django 5.2.17 on 2026-08-25 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hospital_slug'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecollection',
            name='barcode',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='samplecollection',
            constraint=models.UniqueConstraint(fields=('hospital', 'barcode'), name='unique_samplecollection_barcode_per_hospital'),
        ),
    ]
