# Generated by Django 5.2.17 on 2026-09-23 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('laboratory', '0002_alter_samplecollection_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='ipd.admission'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='priority',
            field=models.CharField(default='routine', help_text='routine | urgent | stat', max_length=8),
        ),
        migrations.AddField(
            model_name='labresult',
            name='interpretation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labresult',
            name='is_amended',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='needs_repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labresult',
            name='repeat_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labresult',
            name='repeated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeats', to='laboratory.labresult'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='source',
            field=models.CharField(default='manual', help_text='manual | analyzer', max_length=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='container',
            field=models.CharField(blank=True, help_text='e.g. Red top, Lavender top', max_length=60),
        ),
        migrations.AddField(
            model_name='labtest',
            name='critical_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='critical_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_outsourced',
            field=models.BooleanField(default=False, help_text='Routinely sent to an external lab.'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='loinc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='labtest',
            name='method',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='labtest',
            name='ref_high',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='ref_low',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sample_type',
            field=models.CharField(blank=True, help_text='e.g. Serum, EDTA whole blood, Urine', max_length=60),
        ),
        migrations.AddField(
            model_name='labtest',
            name='tat_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='rejection_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='rejection_reason',
            field=models.CharField(blank=True, help_text='haemolysed | clotted | insufficient | mislabelled | leaked | wrong_container | delayed | other', max_length=40),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='status',
            field=models.CharField(choices=[('collected', 'Collected'), ('in_transit', 'In transit'), ('received', 'Received in lab'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='collected', max_length=12),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='barcode',
            field=models.CharField(blank=True, help_text='Specimen number — auto-assigned when left blank (AAC.3.b).', max_length=64),
        ),
        migrations.CreateModel(
            name='LabAnalyzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('protocol', models.CharField(default='hl7', help_text='hl7 | astm', max_length=10)),
                ('api_token', models.CharField(blank=True, max_length=64)),
                ('test_code_map', models.JSONField(blank=True, default=dict, help_text='Analyser test code -> LabTest.code, e.g. {"GLU": "FBS"}')),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabReportAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='laboratory.laborder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('hematology', 'Hematology'), ('biochemistry', 'Biochemistry'), ('microbiology', 'Microbiology'), ('serology', 'Serology'), ('pathology', 'Pathology'), ('other', 'Other')], default='other', max_length=16)),
                ('header_text', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True, help_text='Method, disclaimers, interpretation notes printed below results.')),
                ('signatory_designation', models.CharField(default='Consultant Pathologist', max_length=120)),
                ('show_previous_result', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='laboratory.labreporttemplate'),
        ),
        migrations.CreateModel(
            name='OutsourcedLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_lab', models.CharField(max_length=150)),
                ('external_reference', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending dispatch'), ('sent', 'Sent'), ('received', 'Result received'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expected_by', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True)),
                ('result_file', models.FileField(blank=True, upload_to='outsourced_reports/%Y/%m/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsourced_tests', to='laboratory.laborder')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
