# Generated by Django 5.2.17 on 2026-09-24 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_consult_started_at_and_more'),
        ('core', '0009_alter_auditlog_action'),
        ('emergency', '0002_edvisit_ambulance_trip_edvisit_brought_by_and_more'),
        ('finance', '0004_doctor_payouts'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CathProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedure_type', models.CharField(choices=[('cag', 'Coronary angiography'), ('ptca', 'PTCA / elective PCI'), ('primary_pci', 'Primary PCI (STEMI)'), ('ppi', 'Permanent pacemaker'), ('icd_crt', 'ICD / CRT'), ('ep_study', 'EP study / ablation'), ('structural', 'Structural (TAVI / BMV / device closure)'), ('peripheral', 'Peripheral angiography / plasty'), ('other', 'Other')], max_length=12)),
                ('urgency', models.CharField(choices=[('elective', 'Elective'), ('urgent', 'Urgent'), ('emergency', 'Emergency / STEMI')], default='elective', max_length=10)),
                ('indication', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='scheduled', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('door_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Sheath in', null=True)),
                ('device_at', models.DateTimeField(blank=True, help_text='First balloon / device (reperfusion)', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Sheath out', null=True)),
                ('delay_reason', models.CharField(blank=True, help_text='Required when a primary PCI misses the door-to-device target', max_length=255)),
                ('access_site', models.CharField(blank=True, help_text='right radial, left radial, right femoral, …', max_length=20)),
                ('sheath_fr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('creatinine_mg_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contrast_agent', models.CharField(blank=True, max_length=60)),
                ('contrast_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('fluoro_minutes', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('air_kerma_mgy', models.PositiveIntegerField(blank=True, null=True)),
                ('dap_gy_cm2', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('heparin_units', models.PositiveIntegerField(blank=True, null=True)),
                ('dominance', models.CharField(blank=True, help_text='right / left / co-dominant', max_length=10)),
                ('lv_ef_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vessel_findings', models.JSONField(blank=True, default=list, help_text='[{"vessel": "LAD", "segment": "proximal", "stenosis_percent": 90, "timi_flow": 2, "intervention": "DES"}]')),
                ('complications', models.JSONField(blank=True, default=list)),
                ('conclusion', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, help_text='medical / pci / cabg / surgery / other', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cath_procedures', to='ipd.admission')),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='appointments.doctor')),
                ('ed_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cath_procedures', to='emergency.edvisit')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cath_procedures', to='appointments.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cath_procedures', to='patients.patient')),
                ('procedure_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.servicetariff')),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CathDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('des', 'Drug-eluting stent'), ('bms', 'Bare-metal stent'), ('balloon', 'Balloon'), ('dcb', 'Drug-coated balloon'), ('pacemaker', 'Pacemaker / ICD generator'), ('lead', 'Lead'), ('occluder', 'Occluder'), ('valve', 'Valve'), ('other', 'Other')], max_length=10)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, help_text='e.g. 3.0 × 28 mm', max_length=40)),
                ('lot_number', models.CharField(max_length=60)),
                ('udi', models.CharField(blank=True, max_length=120)),
                ('serial_number', models.CharField(blank=True, max_length=60)),
                ('vessel', models.CharField(blank=True, max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Billed price (NPPA ceiling for coronary stents)', max_digits=12)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='cathlab.cathprocedure')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cathprocedure',
            index=models.Index(fields=['hospital', 'procedure_type', 'status'], name='cathlab_cat_hospita_2677be_idx'),
        ),
    ]
