"""Build the NABH HIS/EMR compliance matrix from element tags in the source.

Every place that implements an objective element carries its code (e.g. "AAC.1.f",
or a range like "AAC.2.h/i") in a docstring or comment. This script scans backend
and frontend sources for those tags and writes COMPLIANCE_MATRIX.md, so the
matrix stays in step with the code. Elements whose evidence is not tagged can be
recorded in manual_evidence.json ({"AAC.1.a": "patients.PatientViewSet ..."}).

Usage: python docs/nabh/build_matrix.py
"""
import json
import re
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SOURCES = [ROOT / "backend" / "apps", ROOT / "Frontend" / "src"]
CHAPTERS = ["AAC", "COP", "MOM", "DAC", "DOM", "FPM", "HRM", "IMS", "MDC"]
TAG = re.compile(r"\b(" + "|".join(CHAPTERS) + r")\.(\d+)((?:\.[a-z](?:/[a-z])*)?)")


def load_elements():
    levels = json.loads((HERE / "levels.json").read_text(encoding="utf-8"))
    return [(code, level, text) for code, level, text in levels]


def scan():
    hits = defaultdict(set)
    for base in SOURCES:
        for path in base.rglob("*"):
            if path.suffix not in {".py", ".ts", ".tsx"} or "migrations" in path.parts or "node_modules" in path.parts:
                continue
            rel = path.relative_to(ROOT).as_posix()
            for m in TAG.finditer(path.read_text(encoding="utf-8", errors="ignore")):
                chapter, std, letters = m.groups()
                if not letters:
                    hits[f"{chapter}.{std}"].add(rel)  # whole standard
                    continue
                for letter in letters[1:].split("/"):
                    hits[f"{chapter}.{std}.{letter}"].add(rel)
    return hits


def main():
    elements = load_elements()
    hits = scan()
    manual_path = HERE / "manual_evidence.json"
    manual = json.loads(manual_path.read_text(encoding="utf-8")) if manual_path.exists() else {}

    rows, by_chapter, by_status = [], defaultdict(lambda: [0, 0]), defaultdict(int)
    for code, level, text in elements:
        std = code.rsplit(".", 1)[0]
        files = sorted(hits.get(code, set()) | hits.get(std, set()) if code in hits else hits.get(code, set()))
        evidence = ", ".join(f"`{f}`" for f in files[:4]) + (f" +{len(files) - 4}" if len(files) > 4 else "")
        status = "Implemented" if evidence else "Gap"
        if code in manual:
            entry = manual[code] if isinstance(manual[code], dict) else {"evidence": manual[code]}
            evidence = "; ".join(x for x in (evidence, entry["evidence"]) if x)
            status = entry.get("status", "Implemented" if evidence else "Gap")
        chap = code.split(".")[0]
        by_chapter[chap][0] += 1
        by_chapter[chap][1] += status == "Implemented"
        by_status[status] += 1
        rows.append(f"| {code} | {level if level != '?' else ''} | {text.strip()} | {status} | {evidence} |")

    total = sum(v[0] for v in by_chapter.values())
    done = sum(v[1] for v in by_chapter.values())
    out = [
        "# NABH HIS/EMR compliance matrix",
        "",
        "Generated by `docs/nabh/build_matrix.py` from element tags in the source. Do not edit by hand;",
        "add a tag next to the implementing code, or an entry in `manual_evidence.json`, and re-run.",
        "",
        "Source: NABH Digital Health Standards for HIS/EMR (v1.2.1) and the Oncology annexure, with their test cases (PDFs in this folder).",
        "",
        f"**{done} of {total} objective elements implemented.** "
        + " · ".join(f"{k}: {v}" for k, v in sorted(by_status.items()) if k != "Implemented"),
        "",
        "Statuses: **Implemented** (code evidence); **Partial** (built, but part of it needs an outside step such as gateway onboarding);",
        "**Deferred** (postponed by product decision); **Organisational** (a process/certification the hospital or vendor holds, not a software feature);",
        "**Gap** (not built yet).",
        "",
        "| Chapter | Elements | Implemented |",
        "|---|---|---|",
        *[f"| {c} | {by_chapter[c][0]} | {by_chapter[c][1]} |" for c in CHAPTERS if c in by_chapter],
        "",
        "Level is Core / Commitment / Achievement / Excellence where the standard's OCR gave it; blank where it could not be read.",
        "",
        "| Element | Level | Requirement | Status | Evidence |",
        "|---|---|---|---|---|",
        *rows,
        "",
    ]
    (HERE / "COMPLIANCE_MATRIX.md").write_text("\n".join(out), encoding="utf-8")
    print(f"{done}/{total} implemented; {dict(by_status)}")
    for row in rows:
        if "| Implemented |" not in row:
            print(row[:140])


if __name__ == "__main__":
    main()
