# Generated by Django 5.2.17 on 2026-09-11 14:51

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_hospital_grievance_officer_email_and_more"),
        ("patients", "0014_alter_patient_insurance_policy_number"),
        ("tpa", "0006_claim_tpa_claim_hospita_8b1265_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbhaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Verification in progress"),
                            ("linked", "Linked"),
                            ("failed", "Verification failed"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("aadhaar_otp", "Aadhaar OTP"),
                            ("mobile_otp", "Mobile OTP"),
                            ("existing_abha", "Existing ABHA number/address"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "abha_number",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="14-digit ABHA number, e.g. 12-3456-7890-1234",
                        max_length=32,
                    ),
                ),
                (
                    "abha_address",
                    apps.core.fields.EncryptedCharField(
                        blank=True,
                        help_text="ABHA address / PHR address, e.g. jane.doe@abdm",
                        max_length=64,
                    ),
                ),
                ("gateway_txn_id", models.CharField(blank=True, max_length=100)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abha_link",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("CAREMGT", "Care Management"),
                            ("BTG", "Break the Glass"),
                            ("PUBHLTH", "Public Health"),
                            ("INSPMT", "Insurance / Claim Settlement"),
                        ],
                        default="CAREMGT",
                        max_length=16,
                    ),
                ),
                ("hi_types", models.JSONField(blank=True, default=list)),
                ("date_range_from", models.DateField()),
                ("date_range_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("granted", "Granted"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("gateway_request_id", models.CharField(blank=True, max_length=100)),
                ("consent_artifact_id", models.CharField(blank=True, max_length=100)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "abha_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_requests",
                        to="abdm.abhalink",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abdm_consent_requests",
                        to="patients.patient",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecordFetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("hi_types_fetched", models.JSONField(blank=True, default=list)),
                ("record_count", models.PositiveIntegerField(default=0)),
                (
                    "consent_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetches",
                        to="abdm.consentrequest",
                    ),
                ),
                (
                    "fetched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="NHCXTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("eligibility_check", "Coverage Eligibility Check"),
                            ("pre_auth", "Pre-Authorization"),
                            ("claim", "Claim"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending at payer"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("error", "Gateway error"),
                        ],
                        default="initiated",
                        max_length=16,
                    ),
                ),
                ("nhcx_transaction_id", models.CharField(blank=True, max_length=100)),
                (
                    "gateway_response_summary",
                    models.CharField(blank=True, max_length=255),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preauth_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nhcx_transactions",
                        to="tpa.preauthrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="abhalink",
            index=models.Index(
                fields=["hospital", "status"], name="abdm_abhali_hospita_064571_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consentrequest",
            index=models.Index(
                fields=["hospital", "status"], name="abdm_consen_hospita_6b5d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nhcxtransaction",
            index=models.Index(
                fields=["hospital", "status"], name="abdm_nhcxtr_hospita_ff6ac3_idx"
            ),
        ),
    ]
