# Generated by Django 5.2.17 on 2026-08-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_message_is_read_thread_and_more"),
        ("core", "0004_hospital_lead_webhook_token"),
        ("enquiries", "0003_enquiry_estimated_value"),
        ("patients", "0003_prescription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="enquiries.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_threads",
                to="enquiries.enquiry",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_threads",
                to="patients.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["hospital", "enquiry", "-created_at"],
                name="communicati_hospita_acf8f0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("patient__isnull", False),
                    ("enquiry__isnull", False),
                    _connector="OR",
                ),
                name="message_has_patient_or_enquiry",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                fields=("hospital", "enquiry", "channel"),
                name="unique_thread_per_enquiry_channel",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("patient__isnull", False),
                    ("enquiry__isnull", False),
                    _connector="OR",
                ),
                name="thread_has_patient_or_enquiry",
            ),
        ),
    ]
