# Generated by Django 5.2.17 on 2026-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. "2025-26"', max_length=9, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='tenantinvoice',
            name='unique_tenantinvoice_number_per_hospital',
        ),
        migrations.AlterField(
            model_name='tenantinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
