# Generated by Django 5.2.17 on 2026-10-10 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_permission_ceiling'),
        ('saas_admin', '0002_invoicesequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnPremiseLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_id', models.CharField(max_length=64, unique=True)),
                ('tier', models.CharField(blank=True, max_length=16)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('grace_period_days', models.PositiveSmallIntegerField(default=14)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('max_active_users', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('max_beds', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('machine_fingerprint', models.CharField(help_text='SHA-256 from get_machine_fingerprint, or "*" for any machine.', max_length=128)),
                ('payload', models.JSONField()),
                ('license_file', models.TextField(editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onprem_licenses', to='core.hospital')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
