# Generated by Django 5.2.17 on 2026-10-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin', '0003_onpremiselicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpremiselicense',
            name='deployment_id',
            field=models.CharField(blank=True, help_text='The installation this licence works on.', max_length=64),
        ),
        migrations.AddField(
            model_name='onpremiselicense',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Licence feature keys (apps.licensing.features).'),
        ),
    ]
