# Generated by Django 5.2.17 on 2026-10-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_admin', '0004_onpremiselicense_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseUsageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField()),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('beds', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField()),
                ('seal_ok', models.BooleanField(default=False)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reports', to='saas_admin.onpremiselicense')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
