# Generated by Django 5.2.17 on 2026-08-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospital_lead_webhook_token"),
        ("enquiries", "0004_lead_management_enhancements"),
        ("packages", "0001_initial"),
        ("patients", "0003_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="campregistration",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="camp_registrations",
                to="enquiries.enquiry",
            ),
        ),
        migrations.AddField(
            model_name="campregistration",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="camp_registrations",
                to="patients.patient",
            ),
        ),
        migrations.CreateModel(
            name="CorporateClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "billing_model",
                    models.CharField(
                        choices=[
                            ("per_employee", "Per employee checkup"),
                            ("flat_annual", "Flat annual contract"),
                            ("credit_line", "Pre-paid credit line"),
                        ],
                        default="per_employee",
                        max_length=16,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("contract_start", models.DateField()),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corporate_clients",
                        to="packages.campaign",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="campregistration",
            name="corporate_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="camp_registrations",
                to="packages.corporateclient",
            ),
        ),
    ]
