# Generated by Django 5.0.14 on 2026-08-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Where NPS promoters get routed (§10).'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='owner_mis_whatsapp_number',
            field=models.CharField(blank=True, help_text='Where the daily WhatsApp MIS is sent (§12).', max_length=20),
        ),
    ]
