# Generated by Django 5.2.17 on 2026-08-14 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_hospital_lead_webhook_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner_org_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='next_uhid_sequence',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Next UHID sequence number for this hospital — see apps.patients.Patient._generate_uhid.'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='core.hospitalgroup'),
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(max_length=64)),
                ('field_name', models.CharField(max_length=100)),
                ('previous_value', models.TextField(blank=True)),
                ('corrected_value', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-amended_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_amendm_content_992514_idx')],
            },
        ),
    ]
