# Generated by Django 5.2.17 on 2026-08-14 10:40

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=apps.core.models.default_enabled_modules, help_text='Modules enabled for this hospital SaaS subscription.'),
        ),
    ]
