# Generated by Django 5.2.17 on 2026-08-25 09:54

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_enabled_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[apps.core.models.validate_hospital_slug]),
        ),
    ]
