# Generated by Django 5.2.17 on 2026-09-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_hospital_grievance_officer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("read", "Read"),
                    ("request", "Request"),
                    ("export", "Export"),
                ],
                max_length=16,
            ),
        ),
    ]
