# Generated by Django 5.2.17 on 2026-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='helpline_phone',
            field=models.CharField(blank=True, help_text='Shown on the login page and patient portal, e.g. 1800-123-4567', max_length=30),
        ),
    ]
