# Generated by Django 5.2.17 on 2026-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_crm_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='permission_ceiling',
            field=models.JSONField(blank=True, help_text='"app.codename" permissions the SaaS admin allows this hospital, within its enabled modules; null = everything in those modules. See apps.accounts.permission_catalog.', null=True),
        ),
    ]
