"""Common ICD-10 codes seen in Indian multispecialty hospitals — a working
starter set; load the full classification with `manage.py import_icd10`."""

CODES = [
    ("A01.0", "Typhoid fever", "Infectious"), ("A09", "Infectious gastroenteritis and colitis, unspecified", "Infectious"),
    ("A15.0", "Tuberculosis of lung", "Infectious"), ("A90", "Dengue fever [classical dengue]", "Infectious"),
    ("A91", "Dengue haemorrhagic fever", "Infectious"), ("A92.0", "Chikungunya virus disease", "Infectious"),
    ("A27.9", "Leptospirosis, unspecified", "Infectious"), ("A41.9", "Sepsis, unspecified organism", "Infectious"),
    ("B05.9", "Measles without complication", "Infectious"), ("B15.9", "Hepatitis A without hepatic coma", "Infectious"),
    ("B16.9", "Acute hepatitis B", "Infectious"), ("B20", "HIV disease", "Infectious"),
    ("B50.9", "Plasmodium falciparum malaria, unspecified", "Infectious"), ("B54", "Unspecified malaria", "Infectious"),
    ("C18.9", "Malignant neoplasm of colon, unspecified", "Neoplasms"), ("C34.9", "Malignant neoplasm of bronchus or lung", "Neoplasms"),
    ("C50.9", "Malignant neoplasm of breast, unspecified", "Neoplasms"), ("C53.9", "Malignant neoplasm of cervix uteri", "Neoplasms"),
    ("C61", "Malignant neoplasm of prostate", "Neoplasms"), ("C02.9", "Malignant neoplasm of tongue", "Neoplasms"),
    ("C06.9", "Malignant neoplasm of mouth", "Neoplasms"), ("C16.9", "Malignant neoplasm of stomach", "Neoplasms"),
    ("C22.0", "Hepatocellular carcinoma", "Neoplasms"), ("C73", "Malignant neoplasm of thyroid gland", "Neoplasms"),
    ("C91.0", "Acute lymphoblastic leukaemia", "Neoplasms"), ("D50.9", "Iron deficiency anaemia, unspecified", "Blood"),
    ("D64.9", "Anaemia, unspecified", "Blood"), ("E03.9", "Hypothyroidism, unspecified", "Endocrine"),
    ("E05.9", "Thyrotoxicosis, unspecified", "Endocrine"), ("E10.9", "Type 1 diabetes mellitus without complications", "Endocrine"),
    ("E11.9", "Type 2 diabetes mellitus without complications", "Endocrine"), ("E11.65", "Type 2 diabetes mellitus with hyperglycaemia", "Endocrine"),
    ("E78.5", "Hyperlipidaemia, unspecified", "Endocrine"), ("E86.0", "Dehydration", "Endocrine"),
    ("E87.1", "Hypo-osmolality and hyponatraemia", "Endocrine"), ("F32.9", "Depressive episode, unspecified", "Mental"),
    ("F10.2", "Alcohol dependence syndrome", "Mental"), ("G40.9", "Epilepsy, unspecified", "Nervous"),
    ("G43.9", "Migraine, unspecified", "Nervous"), ("G45.9", "Transient cerebral ischaemic attack", "Nervous"),
    ("H25.9", "Senile cataract, unspecified", "Eye"), ("H40.9", "Glaucoma, unspecified", "Eye"),
    ("H66.9", "Otitis media, unspecified", "Ear"), ("I10", "Essential (primary) hypertension", "Circulatory"),
    ("I20.0", "Unstable angina", "Circulatory"), ("I21.9", "Acute myocardial infarction, unspecified", "Circulatory"),
    ("I25.1", "Atherosclerotic heart disease", "Circulatory"), ("I48", "Atrial fibrillation and flutter", "Circulatory"),
    ("I50.9", "Heart failure, unspecified", "Circulatory"), ("I63.9", "Cerebral infarction, unspecified", "Circulatory"),
    ("I61.9", "Intracerebral haemorrhage, unspecified", "Circulatory"), ("I80.2", "Deep vein thrombosis of lower extremity", "Circulatory"),
    ("I26.9", "Pulmonary embolism without acute cor pulmonale", "Circulatory"), ("J02.9", "Acute pharyngitis, unspecified", "Respiratory"),
    ("J06.9", "Acute upper respiratory infection, unspecified", "Respiratory"), ("J18.9", "Pneumonia, unspecified organism", "Respiratory"),
    ("J44.1", "COPD with acute exacerbation", "Respiratory"), ("J45.9", "Asthma, unspecified", "Respiratory"),
    ("J96.0", "Acute respiratory failure", "Respiratory"), ("K21.9", "Gastro-oesophageal reflux disease without oesophagitis", "Digestive"),
    ("K25.9", "Gastric ulcer, unspecified", "Digestive"), ("K29.7", "Gastritis, unspecified", "Digestive"),
    ("K35.8", "Acute appendicitis, other and unspecified", "Digestive"), ("K40.9", "Inguinal hernia without obstruction or gangrene", "Digestive"),
    ("K70.3", "Alcoholic cirrhosis of liver", "Digestive"), ("K74.6", "Other and unspecified cirrhosis of liver", "Digestive"),
    ("K80.2", "Calculus of gallbladder without cholecystitis", "Digestive"), ("K81.0", "Acute cholecystitis", "Digestive"),
    ("K85.9", "Acute pancreatitis, unspecified", "Digestive"), ("K92.2", "Gastrointestinal haemorrhage, unspecified", "Digestive"),
    ("L03.9", "Cellulitis, unspecified", "Skin"), ("L89.9", "Pressure ulcer, unspecified", "Skin"),
    ("M17.9", "Osteoarthritis of knee, unspecified", "Musculoskeletal"), ("M54.5", "Low back pain", "Musculoskeletal"),
    ("M06.9", "Rheumatoid arthritis, unspecified", "Musculoskeletal"), ("N17.9", "Acute kidney failure, unspecified", "Genitourinary"),
    ("N18.4", "Chronic kidney disease, stage 4", "Genitourinary"), ("N18.5", "Chronic kidney disease, stage 5", "Genitourinary"),
    ("N18.9", "Chronic kidney disease, unspecified", "Genitourinary"), ("N20.0", "Calculus of kidney", "Genitourinary"),
    ("N39.0", "Urinary tract infection, site not specified", "Genitourinary"), ("N40", "Hyperplasia of prostate", "Genitourinary"),
    ("O80", "Single spontaneous delivery", "Pregnancy"), ("O82", "Single delivery by caesarean section", "Pregnancy"),
    ("O14.9", "Pre-eclampsia, unspecified", "Pregnancy"), ("O24.4", "Gestational diabetes mellitus", "Pregnancy"),
    ("O72.1", "Other immediate postpartum haemorrhage", "Pregnancy"), ("P07.3", "Other preterm infants", "Perinatal"),
    ("P59.9", "Neonatal jaundice, unspecified", "Perinatal"), ("P22.0", "Respiratory distress syndrome of newborn", "Perinatal"),
    ("Q21.1", "Atrial septal defect", "Congenital"), ("R50.9", "Fever, unspecified", "Symptoms"),
    ("R07.4", "Chest pain, unspecified", "Symptoms"), ("R10.4", "Other and unspecified abdominal pain", "Symptoms"),
    ("R55", "Syncope and collapse", "Symptoms"), ("R56.9", "Unspecified convulsions", "Symptoms"),
    ("S06.0", "Concussion", "Injury"), ("S06.9", "Intracranial injury, unspecified", "Injury"),
    ("S72.0", "Fracture of neck of femur", "Injury"), ("S82.2", "Fracture of shaft of tibia", "Injury"),
    ("S52.5", "Fracture of lower end of radius", "Injury"), ("T14.9", "Injury, unspecified", "Injury"),
    ("T30.0", "Burn of unspecified body region, unspecified degree", "Injury"), ("T63.0", "Toxic effect of snake venom", "Injury"),
    ("T60.0", "Toxic effect of organophosphate insecticides", "Injury"), ("T78.2", "Anaphylactic shock, unspecified", "Injury"),
    ("V89.2", "Person injured in motor-vehicle accident, traffic", "External causes"), ("W19", "Unspecified fall", "External causes"),
    ("W54", "Bitten or struck by dog", "External causes"), ("X64", "Intentional self-poisoning", "External causes"),
    ("Z00.0", "General medical examination", "Factors"), ("Z23", "Need for immunization", "Factors"),
    ("Z34.9", "Supervision of normal pregnancy", "Factors"), ("Z51.1", "Chemotherapy session for neoplasm", "Factors"),
    ("Z51.0", "Radiotherapy session", "Factors"), ("Z49.1", "Extracorporeal dialysis", "Factors"),
    ("U07.1", "COVID-19, virus identified", "Special"),
]


def seed(model):
    existing = set(model.objects.values_list("code", flat=True))
    model.objects.bulk_create([model(code=c, title=t, chapter=ch) for c, t, ch in CODES if c not in existing])
