# Generated by Django 5.2.17 on 2026-08-14 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_doctor_user'),
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
        ('ipd', '0001_initial'),
        ('patients', '0011_prescription_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_theatre_room', models.CharField(max_length=120)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('anaesthetist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anaesthesia_schedules', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_schedules', to='appointments.doctor')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='OperativeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('procedure_performed', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operative_notes', to='appointments.doctor')),
                ('ot_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operative_note', to='ot.otschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImplantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implant_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ot_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implant_usages', to='ot.otschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumableUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ot_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_usages', to='ot.otschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnaesthesiaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('anaesthesia_type', models.CharField(max_length=120)),
                ('intra_op_notes', models.TextField(blank=True)),
                ('anaesthetist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anaesthesia_records', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ot_schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anaesthesia_record', to='ot.otschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurgeryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_procedure', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_requests', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOpChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('fasting_confirmed', models.BooleanField(default=False)),
                ('site_marked', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('surgery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preop_checklist', to='ot.surgeryrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='otschedule',
            name='surgery_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='ot.surgeryrequest'),
        ),
    ]
