# Generated by Django 5.2.17 on 2026-08-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anaesthesiarecord',
            options={'permissions': [('finalize_anaesthesiarecord', 'Can finalize an anaesthesia record')]},
        ),
        migrations.AlterModelOptions(
            name='operativenote',
            options={'permissions': [('finalize_operativenote', 'Can finalize an operative note')]},
        ),
    ]
