# Generated by Django 5.2.17 on 2026-09-23 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ot', '0002_alter_anaesthesiarecord_options_and_more'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='airway_device',
            field=models.CharField(blank=True, help_text='ETT size, LMA, face mask, none', max_length=60),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='asa_grade',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='complications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='drugs',
            field=models.JSONField(blank=True, default=list, help_text='[{drug, dose, route, time}]'),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='estimated_blood_loss_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='fluids',
            field=models.JSONField(blank=True, default=list, help_text='[{fluid, volume_ml}]'),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='induction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='recovery_aldrete_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='reversal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='shifted_to',
            field=models.CharField(blank=True, help_text='Recovery / ICU / ward', max_length=60),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='urine_output_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anaesthesiarecord',
            name='vitals',
            field=models.JSONField(blank=True, default=list, help_text='[{time, hr, bp, spo2, etco2}]'),
        ),
        migrations.AddField(
            model_name='implantusage',
            name='batch_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='implantusage',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implantusage',
            name='implanted_site',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='implantusage',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='implantusage',
            name='sticker_image',
            field=models.ImageField(blank=True, upload_to='implants/'),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='last_reschedule_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='wheeled_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otschedule',
            name='wheeled_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='airway_assessment',
            field=models.CharField(blank=True, help_text='e.g. Mallampati II', max_length=100),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='asa_grade',
            field=models.CharField(blank=True, help_text='I–VI (E for emergency)', max_length=4),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='assessment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='blood_arranged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='comorbidities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='fit_for_surgery',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='investigations_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='npo_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preopchecklist',
            name='premedication',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='is_unplanned_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='previous_surgery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='ot.surgeryrequest'),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='priority',
            field=models.CharField(default='elective', help_text='elective | urgent | emergency', max_length=12),
        ),
        migrations.AddField(
            model_name='surgeryrequest',
            name='procedure_type',
            field=models.CharField(default='surgery', help_text='surgery | interventional | procedural_sedation (COP.6)', max_length=20),
        ),
        migrations.CreateModel(
            name='SurgicalSafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting', models.CharField(default='ot', help_text='ot | ward | opd | cathlab | endoscopy', max_length=10)),
                ('procedure_name', models.CharField(max_length=255)),
                ('sign_in', models.JSONField(blank=True, default=dict)),
                ('sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('time_out', models.JSONField(blank=True, default=dict)),
                ('time_out_at', models.DateTimeField(blank=True, null=True)),
                ('sign_out', models.JSONField(blank=True, default=dict)),
                ('sign_out_at', models.DateTimeField(blank=True, null=True)),
                ('antibiotic_prophylaxis_indicated', models.BooleanField(default=True)),
                ('antibiotic_given_at', models.DateTimeField(blank=True, null=True)),
                ('antibiotic_given_within_60_min', models.BooleanField(editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ot_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_checklist', to='ot.otschedule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_safety_checklists', to='patients.patient')),
                ('sign_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sign_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('time_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
