import logging
from typing import Any, Dict, List, Optional
from django.utils import timezone
from apps.automation.models import Task, Workflow, WorkflowRun, WorkflowStep

logger = logging.getLogger(__name__)


def execute_workflow(
    trigger_type: str,
    event_data: Dict[str, Any],
    hospital_id: Any,
) -> List[WorkflowRun]:
    """Evaluates active workflows matching trigger_type and executes node steps."""
    matching_workflows = Workflow.objects.filter(
        hospital_id=hospital_id,
        trigger_type=trigger_type,
        is_active=True,
    ).prefetch_related("steps")

    runs = []

    for wf in matching_workflows:
        steps = list(wf.steps.all())
        step_logs = []
        status = WorkflowRun.Status.SUCCESS

        for step in steps:
            log_entry = {
                "step_order": step.order,
                "step_type": step.step_type,
                "action_type": step.action_type,
                "title": step.title or f"Step #{step.order}",
                "status": "passed",
                "details": "",
            }

            try:
                # 1. Condition Filter Step
                if step.step_type == WorkflowStep.StepType.CONDITION:
                    cond_expr = step.config.get("condition", "")
                    # Simple evaluation e.g. "score <= 6" or "stage == 'new'"
                    if "score" in event_data and "<=" in cond_expr:
                        threshold = int(cond_expr.split("<=")[-1].strip())
                        if event_data.get("score", 10) > threshold:
                            log_entry["status"] = "skipped"
                            log_entry["details"] = f"Condition failed: score {event_data.get('score')} > {threshold}"
                            step_logs.append(log_entry)
                            break  # Skip remaining steps in this workflow

                # 2. Action Step
                elif step.step_type == WorkflowStep.StepType.ACTION:
                    if step.action_type == WorkflowStep.ActionType.CREATE_TASK:
                        task_title = step.config.get("title", f"Workflow Task: {wf.name}")
                        Task.objects.create(
                            hospital_id=hospital_id,
                            title=task_title,
                            description=f"Auto-generated by Workflow '{wf.name}' trigger '{trigger_type}'",
                            priority=Task.Priority.HIGH if "urgent" in str(event_data).lower() else Task.Priority.NORMAL,
                            status=Task.Status.PENDING,
                        )
                        log_entry["details"] = f"Task created: '{task_title}'"

                    elif step.action_type in [WorkflowStep.ActionType.SEND_WHATSAPP, WorkflowStep.ActionType.SEND_SMS]:
                        msg_template = step.config.get("template", "Default notification message")
                        log_entry["details"] = f"Message queued for dispatch via {step.action_type}: '{msg_template}'"

                    elif step.action_type == WorkflowStep.ActionType.ESCALATE:
                        log_entry["details"] = f"Escalation alert triggered for hospital #{hospital_id}"

                    elif step.action_type == WorkflowStep.ActionType.WAIT_DELAY:
                        delay_mins = step.config.get("delay_minutes", 15)
                        log_entry["details"] = f"Scheduled delay for {delay_mins} minutes"

            except Exception as e:
                logger.error(f"Error executing step #{step.order} in workflow #{wf.id}: {e}")
                status = WorkflowRun.Status.FAILED
                log_entry["status"] = "failed"
                log_entry["details"] = f"Execution error: {str(e)}"
                step_logs.append(log_entry)
                break

            step_logs.append(log_entry)

        run_log = WorkflowRun.objects.create(
            hospital_id=hospital_id,
            workflow=wf,
            trigger_event=trigger_type,
            status=status,
            context=event_data,
            log_output=step_logs,
        )
        runs.append(run_log)

    return runs
