# Generated by Django 5.2.17 on 2026-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_medicaldevice_devicevitalsign_recordshare_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalalert',
            name='alert_type',
            field=models.CharField(choices=[('critical_result', 'Critical result'), ('allergy', 'Allergy'), ('interaction', 'Drug interaction'), ('duplicate_order', 'Duplicate order'), ('contraindication', 'Contraindication'), ('high_risk_medication', 'High-risk medication'), ('notifiable_disease', 'Notifiable disease'), ('early_warning', 'Early warning score'), ('risk', 'Risk assessment'), ('cdss', 'Clinical decision support'), ('expiry', 'Expiry / stock'), ('new_order', 'New order for department')], max_length=24),
        ),
    ]
