# Generated by Django 5.2.17 on 2026-09-24 07:42

from django.db import migrations, models


def install_library(apps, schema_editor):
    """Existing hospitals get the specialty library too (new ones get it at seeding)."""
    from apps.clinical.specialty_templates import install_specialty_library

    Hospital = apps.get_model("core", "Hospital")
    AssessmentTemplate = apps.get_model("clinical", "AssessmentTemplate")
    for hospital in Hospital.objects.filter(pk__in=AssessmentTemplate.objects.values("hospital")):
        install_specialty_library(hospital, apps.get_model)


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_alert_new_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='category',
            field=models.CharField(choices=[('general', 'General medicine'), ('antenatal', 'Antenatal'), ('obstetrics', 'Obstetrics'), ('paediatrics', 'Paediatrics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('oncology', 'Oncology'), ('surgery', 'Surgery'), ('nursing', 'Nursing'), ('dietary', 'Dietary'), ('rehab', 'Rehabilitation'), ('psychiatry', 'Psychiatry'), ('orthopaedics', 'Orthopaedics'), ('cardiology', 'Cardiology'), ('gynaecology', 'Gynaecology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('urology', 'Urology'), ('endocrinology', 'Endocrinology / Diabetes'), ('dental', 'Dental')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicalassessment',
            name='category',
            field=models.CharField(choices=[('general', 'General medicine'), ('antenatal', 'Antenatal'), ('obstetrics', 'Obstetrics'), ('paediatrics', 'Paediatrics'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('oncology', 'Oncology'), ('surgery', 'Surgery'), ('nursing', 'Nursing'), ('dietary', 'Dietary'), ('rehab', 'Rehabilitation'), ('psychiatry', 'Psychiatry'), ('orthopaedics', 'Orthopaedics'), ('cardiology', 'Cardiology'), ('gynaecology', 'Gynaecology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('nephrology', 'Nephrology'), ('urology', 'Urology'), ('endocrinology', 'Endocrinology / Diabetes'), ('dental', 'Dental')], default='general', max_length=20),
        ),
        migrations.RunPython(install_library, migrations.RunPython.noop),
    ]
