# Generated by Django 5.2.17 on 2026-09-24 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('general', 'General (visiting hours, facilities)'), ('rights', 'Patient rights & responsibilities'), ('education', 'Health education'), ('preparation', 'Test / procedure preparation'), ('discharge', 'Discharge & home care'), ('tariff', 'Tariff / charges')], default='general', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('language', models.CharField(default='en', max_length=4)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PatientReportedMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('prom', 'Outcome (PROM)'), ('prem', 'Experience (PREM)')], max_length=4)),
                ('instrument', models.CharField(help_text='e.g. EQ-5D-5L, PROMIS-10, Inpatient experience', max_length=80)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('comments', models.TextField(blank=True)),
                ('submitted_via', models.CharField(default='portal', max_length=10)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_measures', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
