# Generated by Django 5.0.14 on 2026-08-12 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("answered", "Answered"),
                            ("missed", "Missed"),
                            ("rnr", "Ring no response"),
                            ("busy", "Busy"),
                            ("failed", "Failed"),
                            ("voicemail", "Voicemail"),
                        ],
                        max_length=16,
                    ),
                ),
                ("from_number", models.CharField(db_index=True, max_length=32)),
                ("to_number", models.CharField(blank=True, max_length=32)),
                ("started_at", models.DateTimeField()),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("recording_url", models.URLField(blank=True)),
                ("consent_recorded", models.BooleanField(default=False)),
                (
                    "call_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opd", "OPD"),
                            ("surgical", "Surgical"),
                            ("second_opinion", "Second opinion"),
                            ("billing", "Billing"),
                            ("report", "Report"),
                            ("complaint", "Complaint"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("provider_name", models.CharField(blank=True, max_length=64)),
                (
                    "provider_call_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CallbackTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sla_due_at", models.DateTimeField()),
                ("escalation_level", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_tasks",
                        to="telephony.call",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_tasks",
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="callback_tasks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["sla_due_at"],
            },
        ),
        migrations.CreateModel(
            name="IVRRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(default="mr", max_length=8)),
                ("dial_in_number", models.CharField(blank=True, max_length=32)),
                (
                    "ivr_option_code",
                    models.CharField(
                        blank=True,
                        help_text="Key pressed / intent code from the IVR provider.",
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ivr_routes",
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["hospital", "status", "started_at"],
                name="telephony_c_hospita_459f71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["hospital", "from_number"],
                name="telephony_c_hospita_6bad04_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callbacktask",
            index=models.Index(
                fields=["hospital", "status", "sla_due_at"],
                name="telephony_c_hospita_878428_idx",
            ),
        ),
    ]
