# Generated by Django 5.0.14 on 2026-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ivr_path',
            field=models.CharField(blank=True, help_text='Department/language/option breadcrumb the caller went through before this call was logged.', max_length=255),
        ),
        migrations.AddField(
            model_name='callbacktask',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
