# Generated by Django 5.2.17 on 2026-08-14 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiries", "0004_lead_management_enhancements"),
        ("telephony", "0002_call_ivr_path_callbacktask_attempt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calls",
                to="enquiries.enquiry",
            ),
        ),
    ]
