# Generated by Django 5.2.17 on 2026-09-24 05:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_consult_started_at_and_more'),
        ('core', '0009_alter_auditlog_action'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('registration', 'Registration'), ('consultation', 'Doctor consultation'), ('billing', 'Billing / cash'), ('lab', 'Sample collection'), ('radiology', 'Radiology'), ('pharmacy', 'Pharmacy'), ('vaccination', 'Vaccination'), ('other', 'Other')], max_length=16)),
                ('counter_label', models.CharField(blank=True, help_text="Shown on the display, e.g. 'Counter 3' or 'Room 12'.", max_length=40)),
                ('token_prefix', models.CharField(default='A', max_length=4)),
                ('default_service_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_points', to='appointments.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QueueDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('announcement', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('service_points', models.ManyToManyField(related_name='displays', to='queue_mgmt.servicepoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_date', models.DateField(default=django.utils.timezone.localdate)),
                ('number', models.PositiveIntegerField()),
                ('visitor_name', models.CharField(blank=True, max_length=150)),
                ('priority', models.BooleanField(default=False, help_text='Senior citizen / emergency / differently-abled — served first.')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Being served'), ('done', 'Done'), ('skipped', 'Skipped / no response'), ('cancelled', 'Cancelled')], default='waiting', max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recall_count', models.PositiveSmallIntegerField(default=0)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='appointments.appointment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_tokens', to='patients.patient')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queue_mgmt.servicepoint')),
            ],
            options={
                'ordering': ['-priority', 'number'],
                'constraints': [models.UniqueConstraint(fields=('service_point', 'token_date', 'number'), name='unique_token_per_point_per_day')],
            },
        ),
    ]
