# Generated by Django 5.2.17 on 2026-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('transfer', 'Store transfer')], max_length=20),
        ),
    ]
