# Generated by Django 5.0.14 on 2026-08-12 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('core', '0002_hospital_google_review_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('missed_call', 'Missed Call / Unanswered Call'), ('enquiry_stage_changed', 'Enquiry Stage Changed'), ('appointment_no_show', 'Appointment No-Show'), ('nps_detractor', 'NPS Detractor Rating Received')], default='missed_call', max_length=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_event', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running')], default='success', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('log_output', models.JSONField(blank=True, default=list)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='automation.workflow')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('step_type', models.CharField(choices=[('trigger', 'Trigger Node'), ('condition', 'Condition Filter Node'), ('action', 'Action Node')], default='action', max_length=24)),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task / Callback Task'), ('send_whatsapp', 'Send WhatsApp Notification'), ('send_sms', 'Send SMS Notification'), ('escalate', 'Escalate to Manager / Owner'), ('wait_delay', 'Wait / Delay Timer')], default='create_task', max_length=32)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
