# Generated by Django 5.2.17 on 2026-08-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_workflow_workflowrun_workflowstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("missed_call", "Missed Call / Unanswered Call"),
                    ("enquiry_stage_changed", "Enquiry Stage Changed"),
                    ("appointment_no_show", "Appointment No-Show"),
                    ("nps_detractor", "NPS Detractor Rating Received"),
                    ("patient_recall_due", "Patient Recall Due (scheduled)"),
                ],
                default="missed_call",
                max_length=48,
            ),
        ),
    ]
