# Generated by Django 5.2.17 on 2026-09-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationadministration',
            name='identity_method',
            field=models.CharField(blank=True, choices=[('wristband_scan', 'Wristband barcode scan'), ('two_identifiers', 'Two identifiers verbally confirmed')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='identity_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='route',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='scanned_identifier',
            field=models.CharField(blank=True, help_text='UHID read off the wristband barcode.', max_length=64),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='status',
            field=models.CharField(choices=[('given', 'Given'), ('held', 'Held'), ('refused', 'Refused by patient'), ('missed', 'Missed')], default='given', max_length=10),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='witnessed_by',
            field=models.ForeignKey(blank=True, help_text='Second nurse for high-risk drugs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
