# Generated by Django 5.2.17 on 2026-09-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Short code, also the patient category used for scheme rates, e.g. pmjay, cghs', max_length=12)),
                ('name', models.CharField(max_length=150)),
                ('payer', models.CharField(blank=True, help_text='e.g. State Health Agency, CGHS Directorate', max_length=150)),
                ('billing_mode', models.CharField(choices=[('package', 'Package rates (all-inclusive, e.g. PM-JAY)'), ('rate_list', 'Scheme rate list (e.g. CGHS / ECHS)')], default='package', max_length=10)),
                ('empanelment_number', models.CharField(blank=True, help_text="The hospital's empanelment / HOSP ID", max_length=60)),
                ('preauth_required', models.BooleanField(default=True)),
                ('claim_submission_days', models.PositiveSmallIntegerField(default=15, help_text='Days after discharge to submit the claim')),
                ('copay_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('document_checklist', models.JSONField(blank=True, default=list)),
                ('claim_portal_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary_id', models.CharField(help_text='PM-JAY ID / CGHS card no. / ECHS card no.', max_length=60)),
                ('family_id', models.CharField(blank=True, max_length=60)),
                ('relation', models.CharField(blank=True, help_text='self, spouse, son, …', max_length=30)),
                ('card_valid_to', models.DateField(blank=True, null=True)),
                ('eligibility', models.CharField(choices=[('unverified', 'Not verified'), ('eligible', 'Eligible'), ('ineligible', 'Not eligible')], default='unverified', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_memberships', to='patients.patient')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='schemes.govtscheme')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preauth_submitted', 'Pre-auth submitted'), ('preauth_query', 'Pre-auth query'), ('preauth_approved', 'Pre-auth approved'), ('preauth_rejected', 'Pre-auth rejected'), ('discharged', 'Discharged — claim pending'), ('claim_submitted', 'Claim submitted'), ('claim_query', 'Claim query'), ('claim_approved', 'Claim approved'), ('claim_rejected', 'Claim rejected'), ('settled', 'Settled')], default='draft', max_length=20)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('preauth_number', models.CharField(blank=True, max_length=60)),
                ('preauth_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('preauth_amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preauth_amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preauth_decided_at', models.DateTimeField(blank=True, null=True)),
                ('claim_number', models.CharField(blank=True, max_length=60)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, help_text='Computed when applied to the bill', max_digits=12)),
                ('claim_due_by', models.DateField(blank=True, null=True)),
                ('claim_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduction_reason', models.CharField(blank=True, max_length=255)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_on', models.DateField(blank=True, null=True)),
                ('utr_number', models.CharField(blank=True, max_length=40)),
                ('documents', models.JSONField(blank=True, default=dict, help_text='{checklist item: true/false}')),
                ('history', models.JSONField(blank=True, default=list)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_cases', to='ipd.admission')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='schemes.schemebeneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. HBP 2.0 code SG039A', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_los_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('includes', models.TextField(blank=True, help_text='What the package covers — stay, drugs, implants, follow-up')),
                ('implant_included', models.BooleanField(default=True)),
                ('preauth_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='schemes.govtscheme')),
            ],
            options={
                'ordering': ['scheme__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SchemeCasePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_packages', to='schemes.schemecase')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schemes.schemepackage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='govtscheme',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_scheme_code_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='schemebeneficiary',
            constraint=models.UniqueConstraint(fields=('scheme', 'beneficiary_id'), name='unique_beneficiary_per_scheme'),
        ),
        migrations.AddIndex(
            model_name='schemecase',
            index=models.Index(fields=['hospital', 'status'], name='schemes_sch_hospita_e5e304_idx'),
        ),
        migrations.AddConstraint(
            model_name='schemepackage',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='unique_package_code_per_scheme'),
        ),
        migrations.AddConstraint(
            model_name='schemecasepackage',
            constraint=models.UniqueConstraint(fields=('case', 'package'), name='unique_package_per_case'),
        ),
    ]
