# Generated by Django 5.2.17 on 2026-09-23 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0004_admission_episode'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('db_latency_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-beat_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('purpose', models.CharField(default='general', help_text='crash_cart | stock_audit | emergency_protocol | administration | general', max_length=40)),
                ('items', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('responses', models.JSONField(default=list, help_text='[{text, checked, remark}] aligned to template.items.')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('all_passed', models.BooleanField(default=False, editable=False)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='quality.checklisttemplate')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=200)),
                ('protocol', models.TextField(blank=True)),
                ('responder_roles', models.JSONField(blank=True, default=list, help_text="Role templates alerted, e.g. ['doctor','nurse','icu_staff'].")),
                ('target_response_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('responders', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=150)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_drill', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='quality.emergencycode')),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_code', models.CharField(max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numerator', models.DecimalField(decimal_places=2, max_digits=14)),
                ('denominator', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-period_start', 'kpi_code'],
            },
        ),
        migrations.CreateModel(
            name='MockDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('variations_observed', models.PositiveSmallIntegerField(default=0)),
                ('observations', models.TextField(blank=True)),
                ('corrective_actions', models.TextField(blank=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drills', to='quality.emergencycode')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-drill_date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.CharField(choices=[('fall', 'Patient fall'), ('medication_error', 'Medication error'), ('adr', 'Adverse drug reaction'), ('transfusion_reaction', 'Transfusion reaction (haemovigilance)'), ('pressure_ulcer', 'Hospital-acquired pressure ulcer'), ('wrong_site', 'Wrong site / patient / procedure'), ('retained_item', 'Retained foreign object'), ('needlestick', 'Needlestick injury'), ('equipment', 'Equipment failure'), ('identification', 'Patient identification error'), ('diagnostic', 'Diagnostic / reporting error'), ('violence', 'Violence / security'), ('unexpected_death', 'Unexpected death'), ('other', 'Other')], max_length=24)),
                ('harm', models.CharField(choices=[('near_miss', 'Near miss (did not reach patient)'), ('no_harm', 'Reached patient — no harm'), ('mild', 'Mild harm'), ('moderate', 'Moderate harm'), ('severe', 'Severe harm'), ('death', 'Death')], default='no_harm', max_length=10)),
                ('is_sentinel', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('immediate_action', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under investigation'), ('rca_done', 'RCA completed'), ('closed', 'Closed')], default='reported', max_length=14)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('capa_due', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to='ipd.admission')),
                ('capa_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to='patients.patient')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('staff_involved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.CharField(max_length=200)),
                ('stage', models.CharField(choices=[('prescribing', 'Prescribing'), ('transcribing', 'Transcribing'), ('dispensing', 'Dispensing'), ('administration', 'Administration'), ('monitoring', 'Monitoring')], max_length=16)),
                ('error_type', models.CharField(choices=[('wrong_drug', 'Wrong drug'), ('wrong_dose', 'Wrong dose / overdose'), ('wrong_route', 'Wrong route'), ('wrong_time', 'Wrong time / omission'), ('wrong_patient', 'Wrong patient'), ('allergy', 'Known allergy'), ('interaction', 'Drug interaction'), ('lasa', 'Look-alike / sound-alike mix-up'), ('abbreviation', 'Error-prone abbreviation / illegible'), ('expired', 'Expired drug'), ('other', 'Other')], max_length=16)),
                ('category', models.CharField(choices=[('A', 'A — circumstances with capacity to cause error'), ('B', 'B — error occurred, did not reach patient'), ('C', 'C — reached patient, no harm'), ('D', 'D — reached patient, needed monitoring'), ('E', 'E — temporary harm, intervention needed'), ('F', 'F — temporary harm, prolonged hospitalisation'), ('G', 'G — permanent harm'), ('H', 'H — intervention to sustain life'), ('I', 'I — death')], default='C', max_length=1)),
                ('prescribed', models.CharField(blank=True, help_text='What was intended.', max_length=200)),
                ('actual', models.CharField(blank=True, help_text='What actually happened.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_errors', to='patients.patient')),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_error', to='quality.safetyincident')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_response', models.CharField(blank=True, max_length=60)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quality.codeactivation')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['responded_at'],
                'constraints': [models.UniqueConstraint(fields=('activation', 'staff'), name='one_response_per_staff_per_activation')],
            },
        ),
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_code', models.CharField(max_length=10)),
                ('kpi_name', models.CharField(max_length=200)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('numerator', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('denominator', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.CharField(default='system', help_text='system | manual | unavailable', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['period_start', 'kpi_code'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'kpi_code', 'period_start', 'period_end'), name='unique_kpi_snapshot_per_period')],
            },
        ),
    ]
