# Generated by Django 5.0.14 on 2026-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attendant_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patient',
            name='attendant_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='attendant_relation',
            field=models.CharField(blank=True, help_text='e.g. daughter, spouse', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='referring_doctor_name',
            field=models.CharField(blank=True, help_text="External referring doctor, free text — not necessarily in this hospital's Doctor table.", max_length=150),
        ),
    ]
