# Generated by Django 5.2.17 on 2026-08-14 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospital_lead_webhook_token"),
        ("patients", "0003_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary contact/household head for this patient, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="next_recall_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="recall_reason",
            field=models.CharField(
                blank=True,
                help_text="e.g. annual checkup, post-surgery follow-up, chronic-care review",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="relationship_to_guardian",
            field=models.CharField(
                blank=True, help_text="e.g. child, spouse, parent", max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["hospital", "next_recall_due_at"],
                name="patients_pa_hospita_e45447_idx",
            ),
        ),
    ]
