# Generated by Django 5.2.17 on 2026-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id_number',
            field=models.TextField(blank=True),
        ),
    ]
