# Generated by Django 5.2.17 on 2026-08-14 06:46

import apps.core.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_encrypt_national_id_and_insurance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_policy_number',
            field=apps.core.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id_number',
            field=apps.core.encryption.EncryptedTextField(blank=True),
        ),
    ]
