# Generated by Django 5.2.17 on 2026-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_switch_national_id_and_insurance_fields_to_encrypted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('access_clinical_detail', 'Can access clinical detail on patient records')]},
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a_positive', 'A+'), ('a_negative', 'A-'), ('b_positive', 'B+'), ('b_negative', 'B-'), ('ab_positive', 'AB+'), ('ab_negative', 'AB-'), ('o_positive', 'O+'), ('o_negative', 'O-')], max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, help_text='Legacy/external MRN, for hospitals migrating from another system.', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('emergency', 'Emergency')], max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='uhid',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
