# Generated by Django 5.2.17 on 2026-08-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
        ('patients', '0010_backfill_uhid'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='opd.encounter'),
        ),
    ]
