# Generated by Django 5.2.17 on 2026-09-11 03:17

import apps.core.fields
from django.db import migrations, models


def encrypt_existing_data(apps, schema_editor):
    """One-time re-save of every existing row so plaintext values written
    before this migration get encrypted under the new field classes, and
    the new blind-index columns (mobile_hash/alternate_mobile_hash) get
    populated (Part A #2).

    Encryption itself needs no manual crypto here — it's transparent at
    the ORM layer (see apps.core.fields): reading a not-yet-encrypted
    value back out returns it verbatim (apps.core.encryption.
    decrypt_value's InvalidToken fallback for a value that was never a
    Fernet token), and saving it back out through the now-encrypted field
    class encrypts it. Only the hash columns, which have no field-level
    equivalent, need computing by hand — and only for Patient, since
    that's the only model with a blind-index lookup path."""
    from apps.core.encryption import blind_index, normalize_phone

    Patient = apps.get_model("patients", "Patient")
    for patient in Patient.objects.all().iterator():
        patient.mobile_hash = blind_index(normalize_phone(patient.mobile))
        patient.alternate_mobile_hash = blind_index(normalize_phone(patient.alternate_mobile))
        patient.save(update_fields=[
            "mobile", "alternate_mobile", "national_id_number", "address",
            "mobile_hash", "alternate_mobile_hash",
        ])

    Document = apps.get_model("patients", "Document")
    for document in Document.objects.all().iterator():
        document.save(update_fields=["notes"])

    Prescription = apps.get_model("patients", "Prescription")
    for prescription in Prescription.objects.all().iterator():
        prescription.save(update_fields=["diagnosis", "symptoms", "medications", "lab_orders", "notes"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_hospital_lead_webhook_token"),
        ("patients", "0011_prescription_encounter"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="patient",
            name="patients_pa_hospita_aaa0b5_idx",
        ),
        migrations.AddField(
            model_name="patient",
            name="alternate_mobile_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mobile_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="notes",
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="alternate_mobile",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mobile",
            field=apps.core.fields.EncryptedCharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id_number",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=apps.core.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="lab_orders",
            field=apps.core.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medications",
            field=apps.core.fields.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="notes",
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="symptoms",
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["hospital", "mobile_hash"],
                name="patients_pa_hospita_4a77a1_idx",
            ),
        ),
        migrations.RunPython(encrypt_existing_data, noop_reverse),
    ]
