# Generated by Django 5.2.17 on 2026-09-11 12:03
"""Restores insurance_policy_number to encrypted-at-rest (Part A #2) and
closes the same gap for attendant_phone.

insurance_policy_number was already EncryptedTextField as of migration 0008
— a merge conflict resolution silently reverted the model field to plain
CharField, and an earlier version of this migration would have codified
that regression at the DB level (ALTER COLUMN TYPE varchar(100), which
would corrupt or fail against any row already holding Fernet ciphertext
longer than 100 chars). This version does the opposite: (re-)encrypts.

Same one-migration pattern as 0012_encrypt_mobile_and_document_notes:
AlterField first (so the field class starts encrypting on write /
tolerates plaintext on read via decrypt_value's InvalidToken fallback),
then RunPython re-saves every row so any still-plaintext value gets
encrypted in place.
"""
from django.db import migrations

import apps.core.fields


def encrypt_existing_data(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    for patient in Patient.objects.all().iterator():
        patient.save(update_fields=["insurance_policy_number", "attendant_phone"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0013_document_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="insurance_policy_number",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="attendant_phone",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.RunPython(encrypt_existing_data, noop_reverse),
    ]
