# Generated by Django 5.2.17 on 2026-09-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='offline_client_id',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated id for idempotent offline sync.', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_preference',
            field=models.CharField(blank=True, help_text='cash | card | upi | insurance | corporate', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_channel',
            field=models.CharField(default='front_desk', help_text='front_desk | kiosk | website | app | qr | abdm_scan_share | offline', max_length=16),
        ),
        migrations.CreateModel(
            name='MobileOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_hash', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(default='registration', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UHIDConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=10)),
                ('branch_code', models.CharField(blank=True, max_length=10)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('pattern', models.CharField(default='{PREFIX}{BRANCH}{YY}{SEQ}', max_length=80)),
                ('sequence_digits', models.PositiveSmallIntegerField(default=6)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uhid_config', to='core.hospital')),
            ],
        ),
    ]
