# Generated by Django 5.2.17 on 2026-09-24 05:58

import apps.telemedicine.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_consult_started_at_and_more'),
        ('core', '0009_alter_auditlog_action'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('mode', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('chat', 'Text / chat')], default='video', max_length=6)),
                ('room_name', models.CharField(default=apps.telemedicine.models._room, editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Patient waiting'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No-show')], default='scheduled', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_follow_up', models.BooleanField(default=False)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('patient_joined_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsultation', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teleconsultations', to='appointments.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultations', to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.prescription')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
