# Generated by Django 5.2.17 on 2026-09-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('chapter', models.CharField(blank=True, max_length=120)),
                ('is_billable', models.BooleanField(default=True)),
                ('snomed_code', models.CharField(blank=True, help_text='Optional SNOMED CT concept mapping.', max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CodingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedures', models.JSONField(blank=True, default=list, help_text='[{code, description}] — ICD-10-PCS / CPT')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding', to='ipd.admission')),
                ('coded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cause_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mrd.icd10code')),
                ('principal_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mrd.icd10code')),
                ('secondary_diagnoses', models.ManyToManyField(blank=True, related_name='+', to='mrd.icd10code')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_number', models.CharField(editable=False, max_length=40)),
                ('is_mlc', models.BooleanField(default=False)),
                ('rack_location', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Awaiting receipt from ward'), ('in_mrd', 'In MRD'), ('issued', 'Issued'), ('archived', 'Archived (off-site)'), ('destroyed', 'Destroyed'), ('missing', 'Missing')], default='pending', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_file', to='ipd.admission')),
                ('destruction_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_files', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=80)),
                ('purpose', models.CharField(help_text='Follow-up, audit, court, insurance, research ...', max_length=150)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_back', models.DateField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('received_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='mrd.medicalrecordfile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.JSONField(default=dict)),
                ('score_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('deficiencies', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('record_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='mrd.medicalrecordfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicalrecordfile',
            constraint=models.UniqueConstraint(fields=('hospital', 'file_number'), name='unique_mrd_file_number'),
        ),
    ]
