# Generated by Django 5.2.17 on 2026-08-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_hospitalgroup_hospital_next_uhid_sequence_and_more'),
        ('patients', '0011_prescription_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('other', 'Other')], default='tablet', max_length=16)),
                ('unit', models.CharField(blank=True, help_text='e.g. strip of 10, bottle of 100ml', max_length=32)),
                ('reorder_level', models.PositiveIntegerField(default=0, help_text='Total quantity_available across batches at/below this triggers a low-stock flag.')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_records', to='patients.prescription')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='pharmacy.medicinebatch')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('damage', 'Damage'), ('expiry', 'Expiry'), ('correction', 'Correction')], max_length=16)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='pharmacy.medicinebatch')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pharmacy.supplier'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_batch_number_per_medicine'),
        ),
    ]
