# Generated by Django 5.2.17 on 2026-09-24 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0014_alter_patient_insurance_policy_number'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='is_non_formulary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_records', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dispenserecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, help_text='Therapeutic class, e.g. Antibiotic, Antihypertensive', max_length=80),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_code',
            field=models.CharField(blank=True, help_text='SNOMED CT / NRCeS drug registry code.', max_length=40),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='NDPS schedule — narcotic register.'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_formulary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_high_risk',
            field=models.BooleanField(default=False, help_text='High-alert medication (insulin, heparin, KCl, opioids, chemo...).'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_lasa',
            field=models.BooleanField(default=False, help_text='Look-alike / sound-alike.'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_restricted_antimicrobial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='lasa_pair',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='route',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g. 2–8 °C', max_length=60),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='is_quarantined',
            field=models.BooleanField(default=False, help_text='Recalled / on hold — cannot be dispensed.'),
        ),
        migrations.CreateModel(
            name='MedicationReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('admission', 'Admission'), ('transfer', 'Transfer'), ('discharge', 'Discharge')], max_length=10)),
                ('items', models.JSONField(default=list)),
                ('discrepancies_found', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_reconciliations', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_reconciliations', to='patients.patient')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, help_text='CDSCO / manufacturer notice number.', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('batches', models.ManyToManyField(blank=True, related_name='recalls', to='pharmacy.medicinebatch')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recalls', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('restocked', models.BooleanField(default=True, help_text='False = destroyed / not fit for reuse.')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pharmacy.medicinebatch')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyIndent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indent_number', models.CharField(blank=True, editable=False, max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('priority', models.CharField(default='routine', max_length=8)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('partial', 'Partially issued'), ('issued', 'Issued'), ('rejected', 'Rejected')], default='requested', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_indents', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(default='Main pharmacy', max_length=100)),
                ('is_emergency_medication', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyMedicationStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(help_text='e.g. ER crash cart 1, ICU, Ward 3', max_length=100)),
                ('par_level', models.PositiveIntegerField(default=1)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('last_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_stocks', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['location', 'medicine__name'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'location', 'medicine'), name='unique_emergency_med_per_location')],
            },
        ),
    ]
