# Generated by Django 5.0.14 on 2026-08-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_hospital_google_review_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMISLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField()),
                ("summary", models.JSONField(default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_error", models.TextField(blank=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="dailymislog",
            constraint=models.UniqueConstraint(
                fields=("hospital", "report_date"),
                name="unique_mis_log_per_hospital_per_day",
            ),
        ),
    ]
