# Generated by Django 5.2.17 on 2026-09-23 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='storage_location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='tti_screened',
            field=models.BooleanField(default=False, help_text='HIV, HBV, HCV, syphilis, malaria screening done and non-reactive.'),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Bag / segment number.', max_length=40),
        ),
        migrations.AddField(
            model_name='bloodunit',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='crossmatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='delay_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='grouping_done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='reserved_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bloodbank.bloodunit'),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='sample_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='units_requested',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='crossmatchrequest',
            name='urgency',
            field=models.CharField(default='routine', help_text='routine | urgent | emergency', max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='deferral_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donor',
            name='deferred_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donor',
            name='haemoglobin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_voluntary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='bedside_verified_by',
            field=models.ForeignKey(blank=True, help_text='Second person for the two-person bedside check.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='had_reaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='post_vitals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='pre_vitals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='reaction_severity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='transfusion',
            name='reaction_type',
            field=models.CharField(blank=True, help_text='febrile | allergic | haemolytic | TRALI | TACO | anaphylaxis | other', max_length=40),
        ),
    ]
