# Generated by Django 5.2.17 on 2026-09-23 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('radiology', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyorder',
            name='accession_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='clinical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='contraindication_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='is_outsourced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='outsourced_center',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='outsourced_report_file',
            field=models.FileField(blank=True, upload_to='radiology_outsourced/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='patient_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='priority',
            field=models.CharField(default='routine', help_text='routine | urgent | stat', max_length=8),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='status_history',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='radiologyorder',
            name='study_instance_uid',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='radiologyprocedure',
            name='code',
            field=models.CharField(blank=True, help_text='LOINC / SNOMED procedure code.', max_length=40),
        ),
        migrations.AddField(
            model_name='radiologyprocedure',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='radiologyprocedure',
            name='preparation_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiologyprocedure',
            name='uses_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='addendum',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='is_amended',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='radiologyorder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('scheduled', 'Scheduled'), ('arrived', 'Patient arrived'), ('in_progress', 'Scan in progress'), ('completed', 'Completed'), ('reported', 'Reported'), ('cancelled', 'Cancelled')], default='ordered', max_length=16),
        ),
        migrations.CreateModel(
            name='RadiologyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('usg', 'Ultrasound'), ('other', 'Other')], max_length=16)),
                ('room', models.CharField(blank=True, max_length=60)),
                ('start_time', models.TimeField(default='08:00')),
                ('end_time', models.TimeField(default='20:00')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=15)),
                ('ae_title', models.CharField(blank=True, help_text='DICOM AE title for modality worklist.', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadiologyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='radiology.radiologyorder')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='radiology.radiologyequipment')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='dicom/%Y/%m/')),
                ('is_dicom', models.BooleanField(default=False)),
                ('study_instance_uid', models.CharField(blank=True, max_length=128)),
                ('series_instance_uid', models.CharField(blank=True, max_length=128)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=128)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radiology.radiologyorder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadiologyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('usg', 'Ultrasound'), ('other', 'Other')], max_length=16)),
                ('findings', models.TextField()),
                ('impression', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='radiology.radiologyprocedure')),
            ],
            options={
                'ordering': ['modality', 'name'],
            },
        ),
        migrations.AddField(
            model_name='radiologyreport',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radiology.radiologytemplate'),
        ),
    ]
