# Generated by Django 5.2.17 on 2026-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_radiologyorder_accession_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyimage',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
