# Generated by Django 5.2.17 on 2026-08-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="queue_token",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slot",
            name="blocked_reason",
            field=models.CharField(
                blank=True, help_text="e.g. doctor on leave, OT block.", max_length=255
            ),
        ),
    ]
