# Generated by Django 5.2.17 on 2026-09-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consult_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Booking id in the external system (AAC.2.d: aggregator app, ABDM, partner portal).', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='source',
            field=models.CharField(choices=[('crm', 'CRM / front desk'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('portal', 'Patient portal / app'), ('external', 'External system / aggregator'), ('telephone', 'Telephone / IVR'), ('walk_in', 'Walk-in')], default='crm', max_length=16),
        ),
    ]
