# Generated by Django 5.2.17 on 2026-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sterilebatch',
            name='expires_on',
            field=models.DateField(blank=True, help_text="Defaults to sterilised_on + the set's shelf life.", null=True),
        ),
    ]
