# Generated by Django 5.2.17 on 2026-09-24 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('facilities', '0003_alter_bed_status'),
        ('support_services', '0002_alter_sterilebatch_expires_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, max_length=30)),
                ('kind', models.CharField(choices=[('soiled', 'Soiled'), ('infected', 'Infected / isolation (red bag)')], default='soiled', max_length=10)),
                ('status', models.CharField(choices=[('collected', 'Collected'), ('processed', 'Washed'), ('returned', 'Returned')], default='collected', max_length=10)),
                ('vendor', models.CharField(blank=True, help_text='Outsourced laundry; blank = in-house', max_length=150)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('wash_temp_c', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wash_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('disinfectant', models.CharField(blank=True, help_text='e.g. 1% sodium hypochlorite, 30 min', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.ward')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='LinenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('patient', 'Patient linen'), ('ot', 'OT linen / drapes'), ('staff', 'Staff uniforms'), ('other', 'Other')], default='patient', max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Replacement cost per piece', max_digits=10)),
                ('expected_washes', models.PositiveSmallIntegerField(default=150, help_text='Typical life in wash cycles')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LinenStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('par_level', models.PositiveIntegerField(default=0, help_text='Clean pieces the location should hold')),
                ('clean_qty', models.PositiveIntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linen_stock', to='facilities.ward')),
                ('linen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='support_services.linentype')),
            ],
            options={
                'ordering': ['ward__name', 'linen_type__name'],
            },
        ),
        migrations.CreateModel(
            name='LaundryBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_qty', models.PositiveIntegerField()),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('rejected_qty', models.PositiveIntegerField(default=0, help_text='Condemned — torn, stained beyond use')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='support_services.laundrybatch')),
                ('linen_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='support_services.linentype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='linentype',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='unique_linen_type_name'),
        ),
        migrations.AddConstraint(
            model_name='linenstock',
            constraint=models.UniqueConstraint(fields=('hospital', 'ward', 'linen_type'), name='unique_linen_stock_location'),
        ),
        migrations.AddConstraint(
            model_name='linenstock',
            constraint=models.UniqueConstraint(condition=models.Q(('ward__isnull', True)), fields=('hospital', 'linen_type'), name='unique_central_linen_stock'),
        ),
        migrations.AddConstraint(
            model_name='laundrybatchline',
            constraint=models.UniqueConstraint(fields=('batch', 'linen_type'), name='unique_linen_type_per_batch'),
        ),
    ]
