# Generated by Django 5.2.17 on 2026-09-24 06:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_auditlog_action'),
        ('ipd', '0005_admission_admission_checklist_admission_care_team_and_more'),
        ('patients', '0015_patient_mobile_verified_at_patient_offline_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=5, null=True)),
                ('nutritional_risk', models.CharField(blank=True, help_text='low | moderate | high', max_length=20)),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ipd.admission')),
                ('dietitian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_therapeutic', models.BooleanField(default=True)),
                ('default_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('default_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texture', models.CharField(choices=[('regular', 'Regular'), ('soft', 'Soft'), ('minced', 'Minced'), ('pureed', 'Pureed'), ('liquid', 'Liquid'), ('rt_feed', "Ryle's tube feed")], default='regular', max_length=10)),
                ('preference', models.CharField(blank=True, help_text='veg | non_veg | eggetarian | jain | vegan', max_length=20)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('fluid_restriction_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('food_allergies', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('npo', 'Nil by mouth'), ('stopped', 'Stopped')], default='active', max_length=8)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_orders', to='ipd.admission')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('ordered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_orders', to='patients.patient')),
                ('diet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='dietary.diettype')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MealService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField(default=django.utils.timezone.localdate)),
                ('meal', models.CharField(choices=[('early_morning', 'Early morning'), ('breakfast', 'Breakfast'), ('mid_morning', 'Mid-morning'), ('lunch', 'Lunch'), ('evening', 'Evening snack'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime')], max_length=14)),
                ('items', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('prepared', 'Prepared'), ('delivered', 'Delivered'), ('refused', 'Refused by patient'), ('held', 'Held (NPO / procedure)')], default='planned', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('consumption_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('diet_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dietary.dietorder')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['service_date', 'meal'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.CharField(choices=[('early_morning', 'Early morning'), ('breakfast', 'Breakfast'), ('mid_morning', 'Mid-morning'), ('lunch', 'Lunch'), ('evening', 'Evening snack'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime')], max_length=14)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Mon … 6=Sun; blank = every day.', null=True)),
                ('items', models.CharField(max_length=300)),
                ('is_veg', models.BooleanField(default=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('diet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='dietary.diettype')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['diet_type', 'meal'],
            },
        ),
        migrations.AddConstraint(
            model_name='diettype',
            constraint=models.UniqueConstraint(fields=('hospital', 'code'), name='unique_diet_code'),
        ),
        migrations.AddConstraint(
            model_name='mealservice',
            constraint=models.UniqueConstraint(fields=('diet_order', 'service_date', 'meal'), name='one_tray_per_meal'),
        ),
    ]
